In [6]:
import pandas as pd

In [7]:
df1 = pd.read_csv("NCVS_PERSONAL_POPULATION_2014-2018.csv")

In [8]:
df1

,year,weight,gender,race1r,hispanic,ethnic1r,ager,marital2,hincome,popsize,region,msa
0,2014,1307.383680,2,1,2,1,7,3,88,0,3,2
1,2014,2306.155560,1,1,2,1,5,1,88,0,3,2
2,2014,1977.789830,1,1,2,1,5,1,88,0,3,2
3,2014,1362.703000,1,2,2,2,4,1,88,0,3,2
4,2014,0.000000,1,2,2,2,7,4,88,0,3,2
5,2014,0.000000,2,1,2,1,7,4,88,0,3,2
6,2014,1346.120820,2,1,2,1,7,2,6,0,3,2
7,2014,1532.717740,1,1,2,1,7,2,6,0,3,2
8,2014,2275.052010,1,2,2,2,6,1,88,4,2,1
9,2014,1488.484815,2,1,2,1,6,2,7,1,2,2
10,2014,1550.678530,1,1,2,1,6,2,7,1,2,2
11,2014,1913.124895,2,1,2,1,1,1,7,1,2,2
12,2014,0.000000,1,2,2,2,6,2,88,1,3,1
13,2014,1785.953945,2,2,2,2,6,2,88,1,3,1
14,2014,3143.914830,1,2,2,2,1,1,88,1,3,1
15,2014,2571.685895,1,3,2,3,6,4,88,1,3,2
16,2014,3235.024945,2,1,2,1,5,4,88,1,3,2
17,2014,1528.403655,2,2,2,2,6,2,5,1,3,2
18,2014,1642.038650,1,2,2,2,6,2,5,1,3,2
19,2014,2274.299545,2,2,2,2,2,1,5,1,3,2
20,2014,2274.299545,2,2,2,2,1,1,5,1,3,2
21,2014,1552.104640,1,1,1,4,8,2,1,5,2,1
22,2014,1477.952590,2,1,1,4,8,2,1,5,2,1
23,2014,1315.201905,2,1,2,1,8,3,3,1,3,2
24,2014,1557.580090,1,1,2,1,7,2,88,1,3,2
25,2014,1702.149040,2,1,2,1,7,2,88,1,3,2
26,2014,1324.917220,1,1,2,1,8,3,88,1,3,1
27,2014,1331.790745,2,1,2,1,7,2,5,0,3,2
28,2014,1357.599630,1,1,2,1,7,2,5,0,3,2
29,2014,1963.734485,1,1,2,1,7,4,88,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1148966,2018,1395.447220,1,1,2,1,5,1,7,3,4,1
1148967,2018,1486.815080,2,1,2,1,7,2,6,2,4,2
1148968,2018,1572.395030,1,1,1,4,7,2,6,2,4,2
1148969,2018,0.000000,1,1,1,4,5,1,4,2,4,2
1148970,2018,1980.051110,2,1,1,4,6,4,4,2,4,2
1148971,2018,0.000000,2,1,1,4,2,1,4,2,4,2
1148972,2018,3042.598690,2,1,1,4,1,1,4,2,4,2
1148973,2018,1388.406770,1,1,2,1,6,2,88,2,4,2
1148974,2018,0.000000,2,1,2,1,6,2,88,2,4,2
1148975,2018,0.000000,2,1,2,1,5,1,88,2,4,2
1148976,2018,0.000000,2,1,2,1,5,1,88,2,4,2
1148977,2018,2241.938010,1,3,1,4,6,2,2,0,4,2
1148978,2018,1948.404440,2,3,1,4,6,2,2,0,4,2
1148979,2018,3308.592450,2,3,1,4,4,1,2,0,4,2
1148980,2018,2149.918110,1,1,2,1,3,1,7,3,4,1
1148981,2018,2552.590890,2,3,2,3,2,1,7,3,4,1
1148982,2018,1410.278800,2,1,2,1,7,2,7,3,4,1
1148983,2018,1253.672940,1,1,2,1,6,2,7,3,4,1
1148984,2018,1073.402930,2,1,2,1,8,2,88,1,4,2
1148985,2018,1142.912280,1,1,2,1,8,2,88,1,4,2
1148986,2018,1161.988390,1,1,2,1,8,2,88,1,4,1
1148987,2018,1537.079360,2,1,2,1,7,5,88,0,4,2
1148988,2018,1579.657350,1,1,2,1,6,1,5,1,4,1
1148989,2018,1171.363170,1,1,2,1,8,2,7,1,4,2
1148990,2018,0.000000,2,1,2,1,8,2,7,1,4,2
1148991,2018,2045.594500,2,3,1,4,3,1,6,5,4,1
1148992,2018,2767.855980,1,3,1,4,7,2,6,5,4,1
1148993,2018,1890.771420,2,3,1,4,7,2,6,5,4,1
1148994,2018,0.000000,2,3,1,4,5,1,6,5,4,1
1148995,2018,2618.508980,2,3,1,4,3,1,6,5,4,1

In [9]:
df2 = pd.read_csv("NCVS_PERSONAL_VICTIMIZATION_2014-2018.csv")
df2

,year,weight,gender,race1r,hispanic,ethnic1r,ager,marital2,hincome,popsize,...,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
0,2014,5865.87421,1,1,2,1,7,4,1,4,...,2,2,0,1,3,1,1,2.0,2.0,2
1,2014,5091.44483,2,1,1,4,4,1,88,1,...,1,1,3,1,3,1,1,2.0,2.0,3
2,2014,3892.71552,2,3,2,3,5,2,7,4,...,2,2,0,1,4,2,0,0.0,2.0,3
3,2014,1952.02221,1,1,1,4,6,1,1,5,...,1,1,1,1,3,1,0,0.0,2.0,1
4,2014,1952.02221,1,1,1,4,6,1,1,5,...,1,1,1,1,3,1,0,0.0,2.0,1
5,2014,1952.02221,1,1,1,4,6,1,1,5,...,1,1,1,1,3,1,0,0.0,2.0,1
6,2014,2217.30396,1,1,2,1,4,1,7,1,...,1,2,0,1,2,1,0,0.0,2.0,1
7,2014,1768.12536,2,1,1,4,6,2,3,1,...,2,2,0,1,4,2,0,0.0,2.0,3
8,2014,2581.83499,1,1,2,1,1,1,6,0,...,1,2,0,1,2,1,0,0.0,2.0,1
9,2014,2737.85790,2,1,2,1,4,1,7,0,...,2,2,0,1,4,2,0,0.0,2.0,3
10,2014,2359.26640,1,1,2,1,6,4,7,4,...,2,2,0,1,4,2,0,0.0,2.0,1
11,2014,1527.09256,1,1,2,1,7,2,7,1,...,2,3,5,1,4,2,0,0.0,2.0,3
12,2014,1752.71512,1,1,2,1,7,4,7,2,...,1,2,0,1,4,2,0,0.0,2.0,3
13,2014,2804.47315,2,1,1,4,3,1,4,5,...,2,2,0,1,4,2,0,0.0,2.0,3
14,2014,1459.66957,1,1,2,1,7,1,2,4,...,2,3,5,1,4,2,0,0.0,2.0,3
15,2014,1512.99554,2,1,2,1,6,2,7,4,...,1,1,2,1,3,1,0,0.0,1.0,1
16,2014,2689.08001,2,1,2,1,4,1,7,4,...,1,1,2,1,3,1,0,0.0,2.0,1
17,2014,3481.00287,2,1,1,4,4,1,4,0,...,2,1,4,1,3,1,0,0.0,2.0,1
18,2014,2878.71164,1,1,1,4,7,2,88,3,...,2,2,0,1,4,2,0,0.0,2.0,1
19,2014,4246.77654,2,1,1,4,6,4,6,1,...,2,2,0,1,4,2,0,0.0,2.0,5
20,2014,3406.81548,1,1,2,1,6,2,7,2,...,2,2,0,1,4,2,0,0.0,2.0,5
21,2014,3769.26294,1,3,2,3,1,1,6,1,...,2,1,3,1,3,1,0,0.0,2.0,2
22,2014,5729.45686,1,1,2,1,4,1,7,2,...,2,1,3,1,3,1,0,0.0,2.0,3
23,2014,2840.60154,1,1,2,1,7,2,7,3,...,1,1,1,1,2,1,0,0.0,2.0,1
24,2014,2751.54310,2,1,2,1,7,2,7,3,...,2,2,0,1,4,2,0,0.0,2.0,3
25,2014,33632.94690,2,1,2,1,7,2,6,1,...,2,2,0,1,2,1,0,0.0,2.0,4
26,2014,1689.35307,2,1,2,1,7,5,5,0,...,2,1,2,1,3,1,0,0.0,2.0,1
27,2014,1732.74494,2,1,1,4,6,2,88,5,...,1,1,2,1,3,1,0,0.0,2.0,1
28,2014,1732.74494,2,1,1,4,6,2,88,5,...,8,1,2,1,3,1,0,0.0,NaN,1
29,2014,2267.32324,2,1,1,4,1,1,5,1,...,2,2,0,1,1,1,0,0.0,2.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9420,2018,5731.16753,2,1,2,1,2,1,5,1,...,2,2,0,1,4,2,0,0.0,2.0,5
9421,2018,4859.87972,1,1,2,1,1,1,5,1,...,2,2,0,1,4,2,1,1.0,2.0,1
9422,2018,4122.67962,2,2,2,2,5,2,88,5,...,2,1,2,1,3,1,0,0.0,2.0,1
9423,2018,796.55245,2,2,2,2,4,1,1,3,...,2,2,0,1,4,2,0,0.0,2.0,3
9424,2018,796.55245,2,2,2,2,4,1,1,3,...,8,2,0,1,4,2,0,0.0,NaN,5
9425,2018,796.55245,2,2,2,2,4,1,1,3,...,8,2,0,1,4,2,0,0.0,NaN,5
9426,2018,796.55245,2,2,2,2,4,1,1,3,...,8,2,0,1,4,2,0,0.0,NaN,5
9427,2018,796.55245,2,2,2,2,4,1,1,3,...,8,2,0,1,4,2,0,0.0,NaN,5
9428,2018,4023.21890,2,1,2,1,1,1,7,2,...,2,3,5,2,5,3,0,0.0,1.0,3
9429,2018,826.00484,2,1,2,1,7,4,2,1,...,1,2,0,1,4,2,0,0.0,2.0,3
9430,2018,2454.90103,2,1,2,1,2,1,7,1,...,2,2,0,1,4,2,0,0.0,2.0,4
9431,2018,4502.37738,1,1,2,1,6,1,7,0,...,2,2,0,1,4,2,0,0.0,2.0,5
9432,2018,2679.38577,1,1,2,1,8,3,2,1,...,1,2,0,2,5,3,0,0.0,2.0,5
9433,2018,15615.10038,1,1,2,1,7,4,88,2,...,1,1,2,1,3,1,1,2.0,1.0,1
9434,2018,2395.60551,1,1,2,1,7,2,7,1,...,1,1,3,1,3,1,0,0.0,2.0,5
9435,2018,3118.71343,2,1,2,1,5,1,7,4,...,2,2,0,1,4,2,0,0.0,2.0,3
9436,2018,2517.48763,2,1,2,1,8,3,88,2,...,1,2,0,1,4,2,1,1.0,2.0,1
9437,2018,2381.63242,1,1,2,1,6,5,2,1,...,2,3,5,1,4,2,0,0.0,2.0,3
9438,2018,2387.95288,1,1,2,1,4,1,5,1,...,2,2,0,1,2,1,0,0.0,2.0,3
9439,2018,1688.34430,2,1,1,4,5,5,4,1,...,2,2,0,1,4,2,0,0.0,2.0,5
9440,2018,4828.45281,1,1,1,4,1,1,2,1,...,2,1,3,1,3,1,1,1.0,2.0,1
9441,2018,1285.52243,1,1,2,1,6,4,88,1,...,2,2,0,1,4,2,0,0.0,2.0,3
9442,2018,2640.50731,1,2,2,2,5,1,1,4,...,1,3,5,2,5,3,0,0.0,2.0,3
9443,2018,1436.39944,2,1,2,1,6,2,88,2,...,2,2,0,1,1,1,0,0.0,2.0,3
9444,2018,1066.85517,1,1,2,1,1,1,1,0,...,2,2,0,1,4,2,1,1.0,2.0,4
9445,2018,4923.72993,2,1,1,4,2,1,7,1,...,2,3,5,2,5,3,0,0.0,2.0,4
9446,2018,2570.47232,1,2,2,2,7,2,6,1,...,2,2,0,1,4,2,0,0.0,2.0,1
9447,2018,2224.65724,2,1,2,1,6,5,7,1,...,1,2,0,1,4,2,1,1.0,1.0,1
9448,2018,1676.22725,1,2,2,2,8,3,5,1,...,1,1,2,1,3,1,1,1.0,1.0,1
9449,2018,1473.06034,1,1,1,4,3,1,2,4,...,1,1,1,1,2,1,0,0.0,2.0,3

In [10]:
df3 = pd.read_csv("NCVS_HOUSEHOLD_POPULATION_2014-2018.csv")
df3

,year,weight,msa,hincome,hhage,hhgen,hhhisp,hhrace1r,hheth1r,hnumber,popsize,region
0,2014,0.00000,2,99,99,9,99,NaN,NaN,NaN,1,2
1,2014,1566.95606,1,5,2,1,2,1.0,1.0,1.0,2,2
2,2014,1286.39067,3,3,5,1,2,1.0,1.0,1.0,1,4
3,2014,1359.41445,1,88,2,2,2,1.0,1.0,2.0,2,4
4,2014,1398.77126,2,5,4,2,1,1.0,4.0,2.0,1,3
5,2014,1952.41184,1,88,2,2,2,1.0,1.0,1.0,1,3
6,2014,0.00000,1,99,99,9,99,NaN,NaN,NaN,1,3
7,2014,920.44631,2,4,5,1,2,1.0,1.0,2.0,1,3
8,2014,0.00000,1,99,99,9,99,NaN,NaN,NaN,2,3
9,2014,1340.71439,2,7,4,2,2,1.0,1.0,2.0,1,3
10,2014,1440.28655,1,88,5,1,2,1.0,1.0,2.0,5,2
11,2014,1480.86697,3,2,3,2,2,2.0,2.0,3.0,1,3
12,2014,1750.35248,2,5,2,1,2,1.0,1.0,2.0,0,3
13,2014,1540.30546,2,7,3,1,2,2.0,2.0,1.0,1,4
14,2014,1430.20125,2,7,5,1,2,1.0,1.0,2.0,1,3
15,2014,1350.77661,2,1,1,1,2,1.0,1.0,2.0,0,2
16,2014,1523.75470,1,6,2,1,2,3.0,3.0,2.0,2,2
17,2014,1572.58278,3,5,5,1,2,1.0,1.0,2.0,0,3
18,2014,1030.90959,2,88,5,2,2,1.0,1.0,1.0,1,3
19,2014,1283.08455,2,7,3,1,2,3.0,3.0,1.0,1,4
20,2014,1076.61012,1,88,5,2,2,1.0,1.0,2.0,5,2
21,2014,1050.38373,2,7,5,2,2,1.0,1.0,1.0,1,2
22,2014,1439.20782,2,6,4,1,2,1.0,1.0,1.0,1,3
23,2014,1441.44546,2,5,4,2,2,1.0,1.0,2.0,0,3
24,2014,2461.57780,1,2,2,2,2,2.0,2.0,1.0,2,3
25,2014,0.00000,1,99,99,9,99,NaN,NaN,NaN,5,2
26,2014,0.00000,2,99,99,9,99,NaN,NaN,NaN,1,2
27,2014,1566.74143,1,88,4,1,2,1.0,1.0,1.0,2,3
28,2014,1455.88922,2,1,4,2,2,1.0,1.0,3.0,1,2
29,2014,0.00000,2,99,99,9,99,NaN,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
854805,2018,0.00000,3,88,99,9,99,NaN,NaN,NaN,1,1
854806,2018,1344.27420,1,5,5,2,2,2.0,2.0,1.0,5,1
854807,2018,1244.67793,1,88,5,1,2,1.0,1.0,2.0,5,1
854808,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,1,1
854809,2018,0.00000,1,88,99,9,99,NaN,NaN,NaN,5,1
854810,2018,1363.91822,2,7,5,2,2,1.0,1.0,1.0,1,1
854811,2018,1179.73914,2,4,3,2,2,1.0,1.0,3.0,0,1
854812,2018,1223.03156,2,6,5,1,2,1.0,1.0,2.0,1,1
854813,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,1,1
854814,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,1,1
854815,2018,0.00000,1,88,99,9,99,NaN,NaN,NaN,2,1
854816,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,1,1
854817,2018,0.00000,1,5,99,9,99,NaN,NaN,NaN,5,1
854818,2018,0.00000,1,88,99,9,99,NaN,NaN,NaN,5,1
854819,2018,1753.60851,2,88,2,1,2,1.0,1.0,2.0,0,1
854820,2018,1667.79613,2,88,4,1,2,1.0,1.0,1.0,1,1
854821,2018,1147.02102,2,88,4,2,2,1.0,1.0,4.0,1,1
854822,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,0,1
854823,2018,1517.67686,2,2,5,1,2,1.0,1.0,2.0,1,1
854824,2018,1454.88433,1,4,4,2,2,1.0,1.0,3.0,5,1
854825,2018,1295.06496,2,88,5,2,2,1.0,1.0,1.0,0,1
854826,2018,0.00000,2,3,99,9,99,NaN,NaN,NaN,1,1
854827,2018,1304.07543,1,1,3,2,2,2.0,2.0,1.0,5,1
854828,2018,1206.79409,1,5,4,2,2,2.0,2.0,1.0,5,1
854829,2018,0.00000,2,88,99,9,99,NaN,NaN,NaN,1,1
854830,2018,1360.90762,2,5,4,2,2,1.0,1.0,1.0,1,1
854831,2018,1324.43944,1,88,5,2,2,3.0,3.0,3.0,5,1
854832,2018,1062.14710,3,7,4,1,2,1.0,1.0,2.0,1,1
854833,2018,1448.14624,1,3,2,2,2,3.0,3.0,1.0,5,1
854834,2018,1304.92349,3,3,3,2,2,1.0,1.0,4.0,1,1

In [11]:
df4 = pd.read_csv("NCVS_HOUSEHOLD_VICTIMIZATION_2014-2018.csv")
df4

,year,weight,msa,hincome,hhage,hhgen,hhhisp,hhrace1r,hheth1r,hnumber,popsize,region,notify,newcrime,newoff,vicservices,locationr
0,2014,2808.64968,2,6,3,1,2,1,1,2,1,4,1,3,8,2.0,1
1,2014,3006.14087,2,88,3,1,2,1,1,2,2,3,2,3,6,2.0,1
2,2014,2812.22564,2,88,5,1,2,1,1,2,0,4,2,3,8,2.0,1
3,2014,2680.82635,1,6,4,2,2,1,1,1,4,2,2,3,8,2.0,3
4,2014,3869.84046,1,88,2,1,2,2,2,1,2,3,2,3,8,2.0,3
5,2014,3104.80446,1,7,2,1,2,3,3,3,2,3,1,3,8,2.0,3
6,2014,2707.85150,2,7,4,2,2,1,1,2,1,4,2,3,8,2.0,1
7,2014,2607.79499,1,88,5,2,2,1,1,2,1,2,2,3,6,2.0,1
8,2014,2775.90891,1,3,3,2,2,2,2,1,2,3,2,3,8,2.0,1
9,2014,2835.57525,2,7,4,2,2,1,1,2,0,4,2,3,8,2.0,5
10,2014,2316.58585,3,88,3,1,2,1,1,3,0,3,2,3,8,2.0,2
11,2014,2698.29790,2,4,2,2,2,1,1,1,0,3,1,3,6,2.0,1
12,2014,2654.15171,1,7,4,1,2,1,1,2,1,3,1,3,8,2.0,5
13,2014,2604.42519,1,6,3,1,2,1,1,3,1,2,2,3,8,2.0,1
14,2014,2386.38921,3,3,3,1,2,1,1,1,0,3,2,3,8,2.0,1
15,2014,3470.07788,2,1,2,2,2,1,1,2,0,3,1,3,8,2.0,1
16,2014,2829.18246,2,88,3,1,2,1,1,3,0,3,1,3,6,2.0,1
17,2014,2829.18246,2,88,3,1,2,1,1,3,0,3,1,3,7,2.0,2
18,2014,4774.58892,2,1,2,2,2,2,2,2,1,3,1,3,6,2.0,1
19,2014,3062.34663,1,88,2,1,2,1,1,1,1,3,1,3,7,2.0,3
20,2014,2835.31462,2,88,2,2,2,1,1,2,1,3,2,3,8,2.0,1
21,2014,2853.33437,1,1,2,2,2,1,1,2,1,2,1,3,8,2.0,3
22,2014,2853.33437,1,1,2,2,2,1,1,2,1,2,1,3,7,2.0,3
23,2014,2650.55566,2,7,2,2,2,3,3,2,1,3,2,3,8,2.0,3
24,2014,2650.55566,2,7,2,2,2,3,3,2,1,3,2,3,8,2.0,5
25,2014,2740.70941,1,4,3,1,2,1,1,1,2,3,1,3,6,NaN,1
26,2014,2874.12215,1,4,3,1,2,1,1,3,2,4,2,3,8,2.0,1
27,2014,2874.12215,1,4,3,1,2,1,1,3,2,4,3,3,8,2.0,1
28,2014,2776.26992,1,2,2,1,2,1,1,1,1,2,2,3,8,2.0,1
29,2014,2580.63058,1,7,5,1,2,1,1,2,4,4,1,3,6,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36248,2018,871.66898,1,88,2,2,2,1,1,3,2,4,2,3,8,2.0,2
36249,2018,1080.35737,1,5,2,2,2,1,1,2,5,4,2,3,8,2.0,1
36250,2018,661.10215,2,7,3,2,2,1,1,3,2,4,1,3,8,2.0,3
36251,2018,528.03518,1,6,3,2,1,3,4,3,4,4,2,3,8,2.0,1
36252,2018,627.29122,1,2,2,2,1,1,4,3,5,4,2,3,8,2.0,1
36253,2018,627.29122,1,2,2,2,1,1,4,3,5,4,1,3,8,2.0,1
36254,2018,627.29122,1,2,2,2,1,1,4,3,5,4,1,3,8,2.0,1
36255,2018,2188.54545,1,7,2,2,1,1,4,1,5,3,1,3,8,2.0,3
36256,2018,2188.54545,1,7,2,2,1,1,4,1,5,3,1,3,8,2.0,3
36257,2018,2023.79230,1,6,5,1,2,1,1,2,5,3,2,3,8,2.0,1
36258,2018,1034.79014,1,6,4,2,1,1,4,2,2,3,1,3,8,2.0,1
36259,2018,444.60231,1,5,2,2,2,1,1,3,1,2,2,3,8,2.0,1
36260,2018,444.60231,1,5,2,2,2,1,1,3,1,2,2,3,8,2.0,1
36261,2018,444.60231,1,5,2,2,2,1,1,3,1,2,2,3,6,2.0,1
36262,2018,441.02777,3,7,3,1,2,1,1,3,0,2,2,3,8,2.0,4
36263,2018,488.93334,1,5,2,1,2,1,1,2,1,2,1,3,6,2.0,1
36264,2018,632.93297,1,7,3,1,2,3,3,3,3,2,2,3,8,2.0,1
36265,2018,677.30214,2,6,4,1,2,1,1,2,0,2,2,3,6,2.0,1
36266,2018,631.83662,1,1,2,2,2,1,1,1,4,2,2,3,8,2.0,1
36267,2018,631.83662,1,1,2,2,2,1,1,1,4,2,2,3,6,2.0,1
36268,2018,631.83662,1,1,2,2,2,1,1,1,4,2,2,3,6,2.0,1
36269,2018,392.65361,2,7,3,2,2,1,1,3,0,2,2,3,8,2.0,3
36270,2018,370.49717,2,7,3,1,2,1,1,3,1,2,2,3,6,2.0,1
36271,2018,465.57475,2,7,4,1,2,3,3,2,1,2,2,3,8,2.0,1
36272,2018,805.30180,1,6,2,1,2,2,2,2,1,2,2,3,8,2.0,1
36273,2018,2631.23396,1,88,1,2,2,1,1,3,1,3,1,3,8,2.0,1
36274,2018,2712.33649,3,2,4,1,2,1,1,2,0,3,1,3,8,2.0,1
36275,2018,343.37620,1,88,3,2,1,1,4,1,3,2,2,3,8,2.0,3
36276,2018,536.34265,1,3,4,2,2,1,1,1,3,2,2,3,8,1.0,3
36277,2018,429.40896,1,7,3,2,2,1,1,2,2,2,1,3,8,NaN,1

In [1]:
import requests 
# Make a get request to get the latest position of the international space station from the opennotify api.
response = requests.get("https://api.usa.gov/crime/fbi/sapi/")

response

In [2]:
response2 = requests.get(" https://www.googleapis.com/civicinfo/v2/elections")

response2

In [3]:
response3 = requests.get("https://www.googleapis.com/civicinfo/v2/divisions")

response3