In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CDRdata.csv")
df

FileNotFoundError: [Errno 2] File b'/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CDRdata.csv' does not exist: b'/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CDRdata.csv'

In [6]:
df = pd.read_csv("/Users/spenc/OneDrive/Documents/University_of_Utah/2019-2020/DataScience/COMP5360Project/project_files/csv_files/CDRdata.csv")
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
...,...,...,...,...,...,...
28131,NaN,Venezuela,2020-03-27 23:23:03,107.0,1.0,31.0
28132,NaN,Vietnam,2020-03-27 23:23:03,163.0,0.0,20.0
28133,NaN,West Bank and Gaza,2020-03-27 23:23:03,91.0,1.0,17.0
28134,NaN,Zambia,2020-03-27 23:23:03,22.0,0.0,0.0
28135,NaN,Zimbabwe,2020-03-27 23:23:03,5.0,1.0,0.0

In [7]:
df.describe()

          Confirmed        Deaths     Recovered
count  28117.000000  27695.000000  27748.000000
mean     269.744141     10.460155     88.591899
std     3165.587133    176.927865   1677.523583
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        1.000000      0.000000      0.000000
75%       14.000000      0.000000      0.000000
max    86498.000000   9134.000000  61732.000000

In [8]:
df["Confirmed"] = df["Confirmed"].fillna(0)
df["Deaths"] = df["Deaths"].fillna(0)
df["Recovered"] = df["Recovered"].fillna(0)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...
28131,NaN,Venezuela,2020-03-27 23:23:03,107.0,1.0,31.0
28132,NaN,Vietnam,2020-03-27 23:23:03,163.0,0.0,20.0
28133,NaN,West Bank and Gaza,2020-03-27 23:23:03,91.0,1.0,17.0
28134,NaN,Zambia,2020-03-27 23:23:03,22.0,0.0,0.0
28135,NaN,Zimbabwe,2020-03-27 23:23:03,5.0,1.0,0.0

In [9]:
df = df[["Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]
df

           Country/Region          Last Update  Confirmed  Deaths  Recovered
0          Mainland China      1/22/2020 17:00        1.0     0.0        0.0
1          Mainland China      1/22/2020 17:00       14.0     0.0        0.0
2          Mainland China      1/22/2020 17:00        6.0     0.0        0.0
3          Mainland China      1/22/2020 17:00        1.0     0.0        0.0
4          Mainland China      1/22/2020 17:00        0.0     0.0        0.0
...                   ...                  ...        ...     ...        ...
28131           Venezuela  2020-03-27 23:23:03      107.0     1.0       31.0
28132             Vietnam  2020-03-27 23:23:03      163.0     0.0       20.0
28133  West Bank and Gaza  2020-03-27 23:23:03       91.0     1.0       17.0
28134              Zambia  2020-03-27 23:23:03       22.0     0.0        0.0
28135            Zimbabwe  2020-03-27 23:23:03        5.0     1.0        0.0

[28136 rows x 5 columns]

In [11]:
countries = ['US', 'Mainland China', 'Italy', 'New Zealand', 'South Korea', 'UK', 'Iran', 'Singapore', 'India', 'Peru']
df = df.loc[df['Country/Region'].isin(countries)]
df

       Country/Region          Last Update  Confirmed  Deaths  Recovered
0      Mainland China      1/22/2020 17:00        1.0     0.0        0.0
1      Mainland China      1/22/2020 17:00       14.0     0.0        0.0
2      Mainland China      1/22/2020 17:00        6.0     0.0        0.0
3      Mainland China      1/22/2020 17:00        1.0     0.0        0.0
4      Mainland China      1/22/2020 17:00        0.0     0.0        0.0
...               ...                  ...        ...     ...        ...
28039            Iran  2020-03-27 23:23:03    32332.0  2378.0    11133.0
28043           Italy  2020-03-27 23:23:03    86498.0  9134.0    10950.0
28078     New Zealand  2020-03-27 23:23:03      368.0     0.0       37.0
28089            Peru  2020-03-27 23:23:03      635.0    11.0       16.0
28105       Singapore  2020-03-27 23:23:03      732.0     2.0      183.0

[22500 rows x 5 columns]

In [18]:
df["Confirmed"] = df["Confirmed"].astype("int")
df["Deaths"] = df["Deaths"].astype("int")
df["Recovered"] = df["Recovered"].astype("int")
df.dtypes

Country/Region    object
Last Update       object
Confirmed          int32
Deaths             int32
Recovered          int32
dtype: object

In [20]:
df.to_csv('/Users/spenc/OneDrive/Documents/University_of_Utah/2019-2020/DataScience/COMP5360Project/project_files/csv_files/CLEANCDRData.csv', index = False)