In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CLEANCDRData.csv")

In [ ]:
from datetime import datetime
groupDate = data.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataChina = data[data["Country/Region"] == "China"]  
dataChina
groupChina = dataChina.groupby("Last Update")
dChina = groupChina.sum()
dChina = list(dChina["Confirmed"].values)
dChina.sort()

dfChina = pd.DataFrame({"China": dChina})
dfChina = pd.concat([dfDate,dfChina], axis=1, sort = False)
dfChina = dfChina.rename(columns={0: "Date"})
dfChina = dfChina.set_index('Date')

In [ ]:
dataUS = data[data["Country/Region"] == "US"]  
groupDate = dataUS.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataUS = data[data["Country/Region"] == "US"]  
dataUS
groupUS = dataUS.groupby("Last Update")
dUS = groupUS.sum()
dUS = list(dUS["Confirmed"].values)
dUS.sort()

dfUS = pd.DataFrame({"US": dUS})
dfUS = pd.concat([dfDate,dfUS], axis=1, sort = False)
dfUS = dfUS.rename(columns={0: "Date"})
dfUS = dfUS.set_index('Date')

In [ ]:
dataIt = data[data["Country/Region"] == "Italy"]  
groupDate = dataIt.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataIt = data[data["Country/Region"] == "Italy"]  
group = dataIt.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"Italy": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfIt = df.set_index('Date')

In [ ]:
dataNZ = data[data["Country/Region"] == "New Zealand"]  
groupDate = dataNZ.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataNZ = data[data["Country/Region"] == "New Zealand"]  
group = dataNZ.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"New Zealand": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfNZ = df.set_index('Date')

In [ ]:
dataSK = data[data["Country/Region"] == "South Korea"]  
groupDate = dataSK.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataSK = data[data["Country/Region"] == "South Korea"]  
group = dataSK.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"South Korea": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfSK = df.set_index('Date')

In [ ]:
dataUK = data[data["Country/Region"] == "United Kingdom"]  
groupDate = dataUK.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataUK = data[data["Country/Region"] == "United Kingdom"]  
group = dataUK.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"United Kingdom": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfUK = df.set_index('Date')

In [ ]:
dataI = data[data["Country/Region"] == "Iran"]  
groupDate = dataI.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataI = data[data["Country/Region"] == "Iran"]  
group = dataI.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"Iran": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfI = df.set_index('Date')

In [ ]:
dataS = data[data["Country/Region"] == "Singapore"]  
groupDate = dataS.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataS = data[data["Country/Region"] == "Singapore"]  
group = dataS.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"Singapore": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfS = df.set_index('Date')

In [ ]:
dataIND = data[data["Country/Region"] == "India"]  
groupDate = dataIND.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataIND = data[data["Country/Region"] == "India"]  
group = dataIND.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"India": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfIND = df.set_index('Date')

In [ ]:
dataP = data[data["Country/Region"] == "Peru"]  
groupDate = dataP.groupby("Last Update")
df1 = groupDate.count()

df1 = list(df1.index.values)
df1.sort(key = lambda date: datetime.strptime(date, '%m/%d/%y'))

dfDate = pd.DataFrame(df1)

In [ ]:
dataP = data[data["Country/Region"] == "Peru"]  
group = dataP.groupby("Last Update")
d = group.sum()
d = list(d["Confirmed"].values)
d.sort()

df = pd.DataFrame({"Peru": d})
df = pd.concat([dfDate,df], axis=1, sort = False)
df = df.rename(columns={0: "Date"})
dfP = df.set_index('Date')

In [ ]:
dfdata = pd.concat([dfChina,dfUS, dfIt, dfSK, dfUK, dfI], axis=1, sort = False)
dfdata

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (25, 15)

fig, axs = plt.subplots(5, 2)
axs[0, 0].plot(dfChina);
axs[0, 0].set_title('China')
axs[0, 1].plot(dfUS)
axs[0, 1].set_title('US')
axs[1, 0].plot(dfIt)
axs[1, 0].set_title('Italy')
axs[1, 1].plot(dfNZ)
axs[1, 1].set_title('New Zealand')
axs[2, 0].plot(dfSK)
axs[2, 0].set_title('South Korea')
axs[2, 1].plot(dfUK)
axs[2, 1].set_title('United Kingdom')
axs[3, 0].plot(dfI)
axs[3, 0].set_title('Iran')
axs[3, 1].plot(dfS)
axs[3, 1].set_title('Singapore')
axs[4, 0].plot(dfIND)
axs[4, 0].set_title('India')
axs[4, 1].plot(dfP)
axs[4, 1].set_title('Peru')

for ax in axs.flat:
    ax.set(xlabel='Date', ylabel='Total Confirmed Cases')
    ax.tick_params(labelrotation=90, axis = 'x')
       
# Hide x labels and tick labels for top plots and y ticks for right plots.
for ax in axs.flat:
    ax.label_outer()

#dfChina.plot(grid = True);
#dfUS.plot(grid = True);
#dfIt.plot(grid = True);
#dfNZ.plot(grid = True);
#dfSK.plot(grid = True);
#dfUK.plot(grid = True);
#dfI.plot(grid = True);
#dfS.plot(grid = True);
#dfIND.plot(grid=True);
#dfP.plot(grid = True);

In [ ]:
dfdata.plot(grid = True);
plt.legend(loc=2, prop={'size': 20})

In [26]:
data = pd.read_csv("/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CLEANCDRData.csv")

In [28]:
dataUS = data[data["Country/Region"] == "US"]  
dataUS

      Country/Region Last Update  Confirmed  Deaths  Recovered
28                US     1/22/20          1       0          0
61                US     1/23/20          1       0          0
97                US     1/24/20          1       0          0
98                US     1/24/20          1       0          0
131               US     1/25/20          1       0          0
132               US     1/25/20          1       0          0
165               US     1/26/20          1       0          0
166               US     1/26/20          1       0          0
167               US     1/26/20          2       0          0
168               US     1/26/20          1       0          0
201               US     1/27/20          1       0          0
202               US     1/27/20          1       0          0
203               US     1/27/20          2       0          0
204               US     1/27/20          1       0          0
237               US     1/28/20          1       0          0
238               US     1/28/20          1       0          0
239               US     1/28/20          2       0          0
240               US     1/28/20          1       0          0
273               US     1/29/20          1       0          0
274               US     1/29/20          1       0          0
275               US     1/29/20          2       0          0
276               US     1/29/20          1       0          0
310               US     1/30/20          1       0          0
311               US     1/30/20          1       0          0
312               US     1/30/20          2       0          0
313               US     1/30/20          1       0          0
350               US     1/31/20          2       0          0
351               US     1/31/20          2       0          0
353               US     1/31/20          1       0          0
354               US     1/31/20          1       0          0
...              ...         ...        ...     ...        ...
24967             US     3/28/20          1       0          0
24968             US     3/28/20          0       0          0
24969             US     3/28/20         13       0          0
24970             US     3/28/20          4       0          0
24971             US     3/28/20          0       0          0
24972             US     3/28/20          0       0          0
24973             US     3/28/20         23       0          0
24974             US     3/28/20          0       0          0
24975             US     3/28/20         16       1          0
24976             US     3/28/20         38       0          0
24977             US     3/28/20          0       0          0
24978             US     3/28/20         37       0          0
24979             US     3/28/20         31       0          0
24980             US     3/28/20          9       1          0
24981             US     3/28/20          1       0          0
24982             US     3/28/20          3       0          0
24983             US     3/28/20          0       0          0
24984             US     3/28/20          4       0          0
24985             US     3/28/20          2       0          0
24986             US     3/28/20          0       0          0
24987             US     3/28/20          0       0          0
24988             US     3/28/20          0       0          0
24989             US     3/28/20          0       0          0
24996             US     3/28/20         49       0          0
25000             US     3/28/20        103       3          0
25001             US     3/28/20         55       1          0
25012             US     3/28/20          0       0          0
25013             US     3/28/20        100       3          0
25014             US     3/28/20          0       0       1072
25018             US     3/28/20         22       0          0

[23032 rows x 5 columns]