In [1]:
import requests

url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-22-2020.csv'
response = requests.get(url)
response

In [2]:
import pandas as pd

In [ ]:
print(response.content)

In [ ]:
df = pd.read_csv(url)
df

In [ ]:
df['Last Update'] = df['Last Update'].apply(lambda x : x[0:7])
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])

df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-23-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-24-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-25-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-26-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-27-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-28-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-29-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-31-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df["Province/State"] = df["Province/State"].replace(states[x], abb[x])
    
df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
df1
df = df.append(df1, ignore_index = True)
df

Changes time format. Adjust the string modifying. Dates Change to (City, State)

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-01-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:6])
mask = df1['Last Update'] == "2/1/20"
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

Time Format Changes again. Adjust string modification.

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-02-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-03-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

In [ ]:
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-04-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-05-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-06-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-07-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-08-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-09-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

Date Format Changes.

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-10-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-11-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-12-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-13-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-14-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-15-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-16-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-17-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-18-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-19-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]


df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-20-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-21-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-22-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-23-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-24-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-25-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-26-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-27-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-28-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-29-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

Change in date format.

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-01-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-02-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-03-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-04-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
    
df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-05-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
    
df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-06-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
    
df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-07-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-08-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")
df1["Province/State"] = df1["Province/State"].replace("Washington, D.C.", "DC")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-09-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:7] + "/" + x[9] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")
df1["Province/State"] = df1["Province/State"].replace("Washington, D.C.", "DC")

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

df1
df = df.append(df1, ignore_index = True)
df

Change in Date Format. Change in State Format.

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-10-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df1
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-12-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-14-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-15-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-16-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-18-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-19-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-21-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/" + "20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
df = df.append(df1, ignore_index = True)
df

Changes Formats for time.

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[0:7])
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

Format Changes for Date

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-24-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-25-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-26-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-28-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-29-2020.csv'
response = requests.get(url)
response

In [ ]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : x[6:10] + "/20")
df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
df1

df = df.append(df1, ignore_index = True)
df

In [ ]:
#df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CDRdata.csv', index = False)

The beginning of the LatLon Code.

In [3]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-01-2020.csv'
response = requests.get(url)
response

In [4]:
df = pd.read_csv(url)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
95,NaN,Belarus,2020-02-28T16:23:03,1,0,0,53.7098,27.9534
96,NaN,Cambodia,2020-02-12T07:43:02,1,0,1,11.5500,104.9167
97,"Montreal, QC",Canada,2020-02-28T05:23:07,1,0,0,45.5017,-73.5673
98,"London, ON",Canada,2020-02-12T18:53:03,1,0,1,42.9849,-81.2453
99,NaN,Dominican Republic,2020-03-01T16:03:06,1,0,0,18.7357,-70.1627
100,NaN,Estonia,2020-02-27T16:23:03,1,0,0,58.5953,25.0136
101,NaN,Ireland,2020-03-01T07:13:07,1,0,0,53.1424,-7.6921
102,NaN,Lithuania,2020-02-28T16:23:03,1,0,0,55.1694,23.8813
103,NaN,Luxembourg,2020-03-01T07:13:07,1,0,0,49.8153,6.1296
104,Tibet,Mainland China,2020-02-12T06:43:02,1,0,1,31.6927,88.0924
105,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
106,NaN,Nepal,2020-02-12T14:43:03,1,0,1,28.1667,84.2500
107,NaN,New Zealand,2020-02-28T16:23:03,1,0,0,-40.9006,174.8860
108,NaN,Nigeria,2020-02-28T16:23:03,1,0,0,9.0820,8.6753
109,NaN,North Macedonia,2020-02-27T16:23:03,1,0,0,41.6086,21.7453
110,NaN,San Marino,2020-03-01T07:13:07,1,0,0,43.9424,12.4578
111,NaN,Sri Lanka,2020-02-08T03:43:03,1,0,1,7.0000,81.0000
112,"Boston, MA",US,2020-02-28T21:13:12,1,0,1,42.3601,-71.0589
113,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
114,"Los Angeles, CA",US,2020-02-01T19:53:03,1,0,0,34.0522,-118.2437
115,"Madison, WI",US,2020-02-05T21:53:02,1,0,0,43.0731,-89.4012
116,"Orange, CA",US,2020-02-01T19:53:03,1,0,0,33.7879,-117.8531
117,"Portland, OR",US,2020-02-29T02:23:11,1,0,0,45.5051,-122.6750
118,"Providence, RI",US,2020-03-01T15:33:03,1,0,0,41.8240,-71.4128
119,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
120,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
121,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
122,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
123,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
124,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [5]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-02-2020.csv'
response = requests.get(url)
response

In [6]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
236,NaN,Luxembourg,2020-03-01T07:13:07,1,0,0,49.8153,6.1296
237,Tibet,Mainland China,2020-02-12T06:43:02,1,0,1,31.6927,88.0924
238,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
239,NaN,Morocco,2020-03-02T22:33:09,1,0,0,31.7917,-7.0926
240,NaN,Nepal,2020-02-12T14:43:03,1,0,1,28.1667,84.2500
241,NaN,New Zealand,2020-02-28T16:23:03,1,0,0,-40.9006,174.8860
242,NaN,Nigeria,2020-02-28T16:23:03,1,0,0,9.0820,8.6753
243,NaN,North Macedonia,2020-02-27T16:23:03,1,0,0,41.6086,21.7453
244,NaN,Saudi Arabia,2020-03-02T23:53:02,1,0,0,24.0000,45.0000
245,NaN,Senegal,2020-03-02T20:23:16,1,0,0,14.4974,-14.4524
246,NaN,Sri Lanka,2020-02-08T03:43:03,1,0,1,7.0000,81.0000
247,"Boston, MA",US,2020-02-28T21:13:12,1,0,1,42.3601,-71.0589
248,"Grafton County, NH",US,2020-03-02T20:33:02,1,0,0,43.9088,-71.8260
249,"Hillsborough, FL",US,2020-03-02T03:13:25,1,0,0,27.9904,-82.3018
250,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
251,"Los Angeles, CA",US,2020-02-01T19:53:03,1,0,0,34.0522,-118.2437
252,"Madison, WI",US,2020-02-05T21:53:02,1,0,0,43.0731,-89.4012
253,"New York City, NY",US,2020-03-02T01:53:03,1,0,0,40.7128,-74.0060
254,"Orange, CA",US,2020-02-01T19:53:03,1,0,0,33.7879,-117.8531
255,"Placer County, CA",US,2020-03-02T23:53:02,1,0,0,39.0916,-120.8039
256,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
257,"San Mateo, CA",US,2020-03-02T20:43:02,1,0,0,37.5630,-122.3255
258,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
259,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
260,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
261,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
262,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
263,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
264,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
265,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [7]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-03-2020.csv'
response = requests.get(url)
response

In [8]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
387,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
388,NaN,Morocco,2020-03-03T15:33:02,1,0,0,31.7917,-7.0926
389,NaN,Nepal,2020-02-12T14:43:03,1,0,1,28.1667,84.2500
390,NaN,New Zealand,2020-02-28T16:23:03,1,0,0,-40.9006,174.8860
391,NaN,Nigeria,2020-02-28T16:23:03,1,0,0,9.0820,8.6753
392,NaN,North Macedonia,2020-02-27T16:23:03,1,0,0,41.6086,21.7453
393,NaN,Saudi Arabia,2020-03-02T23:53:02,1,0,0,24.0000,45.0000
394,NaN,Sri Lanka,2020-02-08T03:43:03,1,0,1,7.0000,81.0000
395,"Norfolk County, MA",US,2020-03-03T14:33:03,1,0,0,42.1767,-71.1449
396,"Berkeley, CA",US,2020-03-03T23:53:03,1,0,0,37.8715,-122.2730
397,"Boston, MA",US,2020-02-28T21:13:12,1,0,1,42.3601,-71.0589
398,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
399,"Los Angeles, CA",US,2020-02-01T19:53:03,1,0,0,34.0522,-118.2437
400,"Madison, WI",US,2020-03-03T15:53:03,1,0,1,43.0731,-89.4012
401,"Maricopa County, AZ",US,2020-03-03T17:33:02,1,0,0,33.2918,-112.4291
402,"New York City, NY",US,2020-03-02T01:53:03,1,0,0,40.7128,-74.0060
403,"Orange, CA",US,2020-02-01T19:53:03,1,0,0,33.7879,-117.8531
404,"Placer County, CA",US,2020-03-02T23:53:02,1,0,0,39.0916,-120.8039
405,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
406,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
407,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
408,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
409,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
410,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
411,"Westchester County, NY",US,2020-03-03T14:43:03,1,0,0,41.1220,-73.7949
412,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
413,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
414,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
415,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
416,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [9]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-04-2020.csv'
response = requests.get(url)
response

In [10]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
547,NaN,Luxembourg,2020-03-03T00:23:16,1,0,0,49.8144,6.1317
548,Tibet,Mainland China,2020-02-12T06:43:02,1,0,1,31.6927,88.0924
549,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
550,NaN,Morocco,2020-03-03T15:33:02,1,0,0,31.7917,-7.0926
551,NaN,Nepal,2020-02-12T14:43:03,1,0,1,28.1667,84.2500
552,NaN,Nigeria,2020-02-28T16:23:03,1,0,0,9.0820,8.6753
553,NaN,North Macedonia,2020-02-27T16:23:03,1,0,0,41.6086,21.7453
554,NaN,Poland,2020-03-04T15:13:18,1,0,0,51.9194,19.1451
555,NaN,Saudi Arabia,2020-03-02T23:53:02,1,0,0,24.0000,45.0000
556,NaN,Sri Lanka,2020-02-08T03:43:03,1,0,1,7.0000,81.0000
557,NaN,Tunisia,2020-03-04T01:33:07,1,0,0,34.0000,9.0000
558,"Norfolk County, MA",US,2020-03-03T14:33:03,1,0,0,42.1767,-71.1449
559,"Berkeley, CA",US,2020-03-03T23:53:03,1,0,0,37.8715,-122.2730
560,"Boston, MA",US,2020-02-28T21:13:12,1,0,1,42.3601,-71.0589
561,"Contra Costa County, CA",US,2020-03-04T04:23:05,1,0,0,37.8534,-121.9018
562,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
563,"Madison, WI",US,2020-03-03T15:53:03,1,0,1,43.0731,-89.4012
564,"Maricopa County, AZ",US,2020-03-03T17:33:02,1,0,0,33.2918,-112.4291
565,"New York City, NY",US,2020-03-02T01:53:03,1,0,0,40.7128,-74.0060
566,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
567,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
568,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
569,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
570,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
571,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
572,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
573,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
574,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
575,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
576,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [11]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-05-2020.csv'
response = requests.get(url)
response

In [12]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
720,NaN,Nigeria,2020-02-28T16:23:03,1,0,0,9.0820,8.6753
721,NaN,North Macedonia,2020-02-27T16:23:03,1,0,0,41.6086,21.7453
722,NaN,Poland,2020-03-04T15:13:18,1,0,0,51.9194,19.1451
723,NaN,South Africa,2020-03-05T13:53:03,1,0,0,-30.5595,22.9375
724,NaN,Sri Lanka,2020-02-08T03:43:03,1,0,1,7.0000,81.0000
725,NaN,Tunisia,2020-03-04T01:33:07,1,0,0,34.0000,9.0000
726,"Norfolk County, MA",US,2020-03-03T14:33:03,1,0,0,42.1767,-71.1449
727,"Berkeley, CA",US,2020-03-03T23:53:03,1,0,0,37.8715,-122.2730
728,"Boston, MA",US,2020-02-28T21:13:12,1,0,1,42.3601,-71.0589
729,"Clark County, NV",US,2020-03-05T20:53:03,1,0,0,36.0796,-115.0940
730,"Contra Costa County, CA",US,2020-03-04T04:23:05,1,0,0,37.8534,-121.9018
731,"Fort Bend County, TX",US,2020-03-05T01:16:59,1,0,0,29.5693,-95.8143
732,"Grant County, WA",US,2020-03-05T20:23:07,1,0,0,47.1981,-119.3732
733,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
734,"Madison, WI",US,2020-03-03T15:53:03,1,0,1,43.0731,-89.4012
735,"Maricopa County, AZ",US,2020-03-03T17:33:02,1,0,0,33.2918,-112.4291
736,"Queens County, NY",US,2020-03-05T21:43:02,1,0,0,40.7282,-73.7949
737,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
738,"Santa Rosa County, FL",US,2020-03-05T20:03:03,1,0,0,30.7690,-86.9824
739,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
740,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
741,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
742,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
743,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
744,"Williamson County, TN",US,2020-03-05T23:33:03,1,0,0,35.9179,-86.8622
745,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
746,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
747,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
748,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
749,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [13]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-06-2020.csv'
response = requests.get(url)
response

In [14]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
919,"Douglas County, NE",US,2020-03-06T23:33:02,1,0,0,41.3148,-96.1951
920,"Fayette County, KY",US,2020-03-06T23:23:03,1,0,0,38.0606,-84.4803
921,"Floyd County, GA",US,2020-03-06T17:53:03,1,0,0,34.2829,-85.2308
922,"Fort Bend County, TX",US,2020-03-05T01:16:59,1,0,0,29.5693,-95.8143
923,"Grant County, WA",US,2020-03-05T20:23:07,1,0,0,47.1981,-119.3732
924,"Humboldt County, CA",US,2020-02-21T05:13:09,1,0,0,40.7450,-123.8695
925,"Madison, WI",US,2020-03-03T15:53:03,1,0,1,43.0731,-89.4012
926,"Marion County, IN",US,2020-03-06T17:13:12,1,0,0,39.8362,-86.1752
927,"Middlesex County, MA",US,2020-03-06T01:29:39,1,0,0,42.4672,-71.2874
928,"Nassau County, NY",US,2020-03-06T14:43:15,1,0,0,40.6546,-73.5594
929,"Norwell County, MA",US,2020-03-06T02:33:03,1,0,0,42.1615,-70.7928
930,"Ramsey County, MN",US,2020-03-06T23:23:03,1,0,0,44.9964,-93.0616
931,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
932,"Santa Rosa County, FL",US,2020-03-05T20:03:03,1,0,0,30.7690,-86.9824
933,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
934,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
935,"Tempe, AZ",US,2020-02-25T21:23:03,1,0,1,33.4255,-111.9400
936,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
937,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
938,"Washoe County, NV",US,2020-03-06T19:43:02,1,0,0,40.5608,-119.6035
939,"Wayne County, PA",US,2020-03-06T16:13:15,1,0,0,41.6739,-75.2479
940,"Williamson County, TN",US,2020-03-05T23:33:03,1,0,0,35.9179,-86.8622
941,"Yolo County, CA",US,2020-03-06T20:13:14,1,0,0,38.7646,-121.9018
942,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
943,NaN,Vatican City,2020-03-06T15:43:02,1,0,0,41.9029,12.4534
944,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
945,Northern Territory,Australia,2020-03-06T04:33:03,0,0,0,-12.4634,130.8456
946,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
947,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
948,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [15]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-07-2020.csv'
response = requests.get(url)
response

In [16]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
1144,"Jefferson County, WA",US,2020-03-07T16:43:02,1,0,0,47.7425,-123.3040
1145,"Kershaw County, SC",US,2020-03-07T02:03:30,1,0,0,34.3672,-80.5883
1146,"Klamath County, OR",US,2020-03-07T20:13:14,1,0,0,42.6953,-121.6142
1147,"Madera County, CA",US,2020-03-07T20:13:14,1,0,0,37.2519,-119.6963
1148,"Madison, WI",US,2020-03-03T15:53:03,1,0,1,43.0731,-89.4012
1149,"Marion County, IN",US,2020-03-06T17:13:12,1,0,0,39.8362,-86.1752
1150,"Middlesex County, MA",US,2020-03-07T03:53:03,1,0,0,41.9120,-70.7168
1151,"Pierce County, WA",US,2020-03-07T03:13:44,1,0,0,47.0676,-122.1295
1152,"Plymouth County, MA",US,2020-03-07T03:53:03,1,0,0,42.1615,-70.7928
1153,"Ramsey County, MN",US,2020-03-06T23:23:03,1,0,0,44.9964,-93.0616
1154,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
1155,"Santa Cruz County, CA",US,2020-03-07T23:43:03,1,0,0,36.9741,-122.0308
1156,"Santa Rosa County, FL",US,2020-03-05T20:03:03,1,0,0,30.7690,-86.9824
1157,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
1158,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
1159,"Tulsa County, OK",US,2020-03-07T04:43:02,1,0,0,36.1593,-95.9410
1160,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
1161,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
1162,"Washoe County, NV",US,2020-03-06T19:43:02,1,0,0,40.5608,-119.6035
1163,"Wayne County, PA",US,2020-03-06T16:13:15,1,0,0,41.6739,-75.2479
1164,"Williamson County, TN",US,2020-03-05T23:33:03,1,0,0,35.9179,-86.8622
1165,"Yolo County, CA",US,2020-03-06T20:13:14,1,0,0,38.7646,-121.9018
1166,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
1167,NaN,Vatican City,2020-03-06T15:43:02,1,0,0,41.9029,12.4534
1168,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
1169,Northern Territory,Australia,2020-03-06T04:33:03,0,0,0,-12.4634,130.8456
1170,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
1171,"Montgomery County, TX",US,2020-03-07T19:53:02,0,0,0,30.3213,-95.4778
1172,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
1173,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [17]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-08-2020.csv'
response = requests.get(url)
response

In [18]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
1399,"Plymouth County, MA",US,2020-03-07T03:53:03,1,0,0,42.1615,-70.7928
1400,"Polk County, GA",US,2020-03-08T04:13:22,1,0,0,34.0132,-85.1479
1401,"Ramsey County, MN",US,2020-03-06T23:23:03,1,0,0,44.9964,-93.0616
1402,"Riverside County, CA",US,2020-03-08T10:33:03,1,0,0,33.9533,-117.3961
1403,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
1404,"Santa Rosa County, FL",US,2020-03-08T15:33:04,1,1,0,30.7690,-86.9824
1405,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
1406,"Shelby County, TN",US,2020-03-08T16:13:36,1,0,0,35.1269,-89.9253
1407,"Sonoma County, CA",US,2020-03-02T20:53:02,1,0,0,38.5780,-122.9888
1408,"Spokane County, WA",US,2020-03-08T21:53:04,1,0,0,47.6587,-117.4225
1409,"St. Louis County, MO",US,2020-03-08T11:23:08,1,0,0,38.6103,-90.4125
1410,"Suffolk County, NY",US,2020-03-08T16:03:05,1,0,0,40.9849,-72.6151
1411,"Tulsa County, OK",US,2020-03-07T04:43:02,1,0,0,36.1593,-95.9410
1412,"Ulster County, NY",US,2020-03-08T16:23:07,1,0,0,41.8586,-74.3118
1413,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
1414,"Unassigned Location, VT",US,2020-03-08T06:23:05,1,0,0,44.3378,-72.7563
1415,"Unknown Location, MA",US,2020-03-08T21:23:03,1,0,0,42.4072,-71.3824
1416,"Volusia County, FL",US,2020-03-08T03:03:08,1,0,0,29.0280,-81.0755
1417,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
1418,"Wayne County, PA",US,2020-03-06T16:13:15,1,0,0,41.6739,-75.2479
1419,"Williamson County, TN",US,2020-03-05T23:33:03,1,0,0,35.9179,-86.8622
1420,"Yolo County, CA",US,2020-03-06T20:13:14,1,0,0,38.7646,-121.9018
1421,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
1422,NaN,Vatican City,2020-03-06T15:43:02,1,0,0,41.9029,12.4534
1423,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
1424,Northern Territory,Australia,2020-03-06T04:33:03,0,0,0,-12.4634,130.8456
1425,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
1426,"Montgomery County, TX",US,2020-03-07T19:53:02,0,0,0,30.3213,-95.4778
1427,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
1428,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

In [19]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-09-2020.csv'
response = requests.get(url)
response

In [20]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
1665,"Polk County, GA",US,2020-03-08T04:13:22,1,0,0,34.0132,-85.1479
1666,"Ramsey County, MN",US,2020-03-06T23:23:03,1,0,0,44.9964,-93.0616
1667,"Riverside County, CA",US,2020-03-08T10:33:03,1,0,0,33.9533,-117.3961
1668,"Rockingham County, NH",US,2020-03-09T22:43:25,1,0,0,42.9931,-71.0498
1669,"San Antonio, TX",US,2020-02-13T18:53:02,1,0,0,29.4241,-98.4936
1670,"Santa Rosa County, FL",US,2020-03-08T15:33:04,1,1,0,30.7690,-86.9824
1671,"Sarasota, FL",US,2020-03-02T03:23:06,1,0,0,27.3364,-82.5307
1672,"Shasta County, CA",US,2020-03-09T03:43:03,1,0,0,40.7909,-121.8474
1673,"Shelby County, TN",US,2020-03-08T16:13:36,1,0,0,35.1269,-89.9253
1674,"Spartanburg County, SC",US,2020-03-09T00:03:07,1,0,0,34.8606,-81.9535
1675,"Spokane County, WA",US,2020-03-08T21:53:04,1,0,0,47.6587,-117.4225
1676,"St. Louis County, MO",US,2020-03-08T11:23:08,1,0,0,38.6103,-90.4125
1677,"Suffolk County, NY",US,2020-03-08T16:03:05,1,0,0,40.9849,-72.6151
1678,"Tulsa County, OK",US,2020-03-07T04:43:02,1,0,0,36.1593,-95.9410
1679,"Ulster County, NY",US,2020-03-08T16:23:07,1,0,0,41.8586,-74.3118
1680,"Umatilla, OR",US,2020-03-02T20:23:16,1,0,0,45.7750,-118.7606
1681,"Unknown Location, MA",US,2020-03-08T21:23:03,1,0,0,42.4072,-71.3824
1682,"Volusia County, FL",US,2020-03-08T03:03:08,1,0,0,29.0280,-81.0755
1683,"Wake County, NC",US,2020-03-03T20:53:02,1,0,0,35.8032,-78.5661
1684,"Wayne County, PA",US,2020-03-06T16:13:15,1,0,0,41.6739,-75.2479
1685,"Williamson County, TN",US,2020-03-05T23:33:03,1,0,0,35.9179,-86.8622
1686,"Yolo County, CA",US,2020-03-06T20:13:14,1,0,0,38.7646,-121.9018
1687,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
1688,NaN,Vatican City,2020-03-06T15:43:02,1,0,0,41.9029,12.4534
1689,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
1690,Northern Territory,Australia,2020-03-06T04:33:03,0,0,0,-12.4634,130.8456
1691,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,29.3829,-98.6134
1692,"Montgomery County, TX",US,2020-03-07T19:53:02,0,0,0,30.3213,-95.4778
1693,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,41.2545,-95.9758
1694,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0,0,0,38.2721,-121.9399

Date Format Changes.

In [21]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-10-2020.csv'
response = requests.get(url)
response

In [22]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
1871,NaN,Liechtenstein,2020-03-04T01:33:07,1,0,0,47.1400,9.5500
1872,NaN,Lithuania,2020-02-28T16:23:03,1,0,0,55.1694,23.8813
1873,Tibet,Mainland China,2020-02-12T06:43:02,1,0,1,31.6927,88.0924
1874,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
1875,NaN,Mongolia,2020-03-10T06:13:43,1,0,0,46.8625,103.8467
1876,NaN,Nepal,2020-03-10T08:33:03,1,0,1,28.3949,84.1240
1877,NaN,Panama,2020-03-10T06:13:43,1,0,0,8.5380,-80.7821
1878,NaN,Paraguay,2020-03-08T09:13:16,1,0,0,-23.4425,-58.4438
1879,NaN,Saint Barthelemy,2020-03-09T10:43:06,1,0,0,17.9000,-62.8333
1880,NaN,Sri Lanka,2020-03-10T08:33:03,1,0,1,7.8731,80.7718
1881,NaN,Togo,2020-03-07T02:13:09,1,0,0,8.6195,0.8248
1882,Kansas,US,2020-03-10T03:13:17,1,0,0,38.5266,-96.7265
1883,Louisiana,US,2020-03-10T03:13:17,1,0,0,31.1695,-91.8678
1884,Missouri,US,2020-03-10T03:13:17,1,0,0,38.4561,-92.2884
1885,Vermont,US,2020-03-10T03:13:17,1,0,0,44.0459,-72.7107
1886,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
1887,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
1888,Alaska,US,2020-03-10T02:33:04,0,0,0,61.3707,-152.4044
1889,Arkansas,US,2020-03-10T02:33:04,0,0,0,34.9697,-92.3731
1890,Delaware,US,2020-03-10T02:33:04,0,0,0,39.3185,-75.5071
1891,Idaho,US,2020-03-10T02:33:04,0,0,0,44.2405,-114.4788
1892,Maine,US,2020-03-10T02:33:04,0,0,0,44.6939,-69.3819
1893,Michigan,US,2020-03-10T02:33:04,0,0,0,43.3266,-84.5361
1894,Mississippi,US,2020-03-10T02:33:04,0,0,0,32.7416,-89.6787
1895,Montana,US,2020-03-10T02:33:04,0,0,0,46.9219,-110.4544
1896,New Mexico,US,2020-03-10T02:33:04,0,0,0,34.8405,-106.2485
1897,North Dakota,US,2020-03-10T02:33:04,0,0,0,47.5289,-99.7840
1898,South Dakota,US,2020-03-10T02:33:04,0,0,0,44.2998,-99.4388
1899,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
1900,Wyoming,US,2020-03-10T02:33:04,0,0,0,42.7560,-107.3025

In [23]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv'
response = requests.get(url)
response

In [24]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
2087,Saint Barthelemy,France,2020-03-11T20:53:02,1,0,0,17.9000,-62.8333
2088,NaN,Holy See,2020-03-10T19:13:21,1,0,0,41.9029,12.4534
2089,NaN,Jamaica,2020-03-11T18:52:03,1,0,0,18.1096,-77.2975
2090,NaN,Jordan,2020-03-03T15:33:02,1,0,0,31.2400,36.5100
2091,NaN,Liechtenstein,2020-03-04T01:33:07,1,0,0,47.1400,9.5500
2092,NaN,Monaco,2020-02-29T00:33:01,1,0,0,43.7333,7.4167
2093,NaN,Mongolia,2020-03-10T06:13:43,1,0,0,46.8625,103.8467
2094,NaN,Nepal,2020-03-10T08:33:03,1,0,1,28.3949,84.1240
2095,NaN,Reunion,2020-03-11T23:13:07,1,0,0,-21.1151,55.5364
2096,NaN,Togo,2020-03-07T02:13:09,1,0,0,8.6195,0.8248
2097,NaN,Turkey,2020-03-11T03:33:05,1,0,0,38.9637,35.2433
2098,Arkansas,US,2020-03-11T18:52:04,1,0,0,34.9697,-92.3731
2099,Delaware,US,2020-03-11T23:13:06,1,0,0,39.3185,-75.5071
2100,Kansas,US,2020-03-10T03:13:17,1,0,0,38.5266,-96.7265
2101,Missouri,US,2020-03-10T03:13:17,1,0,0,38.4561,-92.2884
2102,Montana,US,2020-03-11T23:13:06,1,0,0,46.9219,-110.4544
2103,Vermont,US,2020-03-10T03:13:17,1,0,0,44.0459,-72.7107
2104,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
2105,Gibraltar,United Kingdom,2020-03-11T20:53:02,1,0,1,36.1408,-5.3536
2106,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
2107,Gansu,Mainland China,2020-03-11T02:18:28,0,0,0,36.0611,103.8343
2108,Hebei,Mainland China,2020-03-11T02:18:29,0,0,0,38.0428,114.5149
2109,Alaska,US,2020-03-10T02:33:04,0,0,0,61.3707,-152.4044
2110,Idaho,US,2020-03-10T02:33:04,0,0,0,44.2405,-114.4788
2111,Maine,US,2020-03-10T02:33:04,0,0,0,44.6939,-69.3819
2112,Mississippi,US,2020-03-10T02:33:04,0,0,0,32.7416,-89.6787
2113,North Dakota,US,2020-03-10T02:33:04,0,0,0,47.5289,-99.7840
2114,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
2115,Wyoming,US,2020-03-10T02:33:04,0,0,0,42.7560,-107.3025
2116,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [25]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-12-2020.csv'
response = requests.get(url)
response

In [26]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
2305,Tibet,China,2020-03-11T02:18:14,1,0,1,31.6927,88.0924
2306,NaN,Congo (Kinshasa),2020-03-11T21:13:24,1,0,0,-4.0383,21.7587
2307,NaN,Cote d'Ivoire,2020-03-12T01:18:01,1,0,0,7.5400,-5.5471
2308,Saint Barthelemy,France,2020-03-11T20:53:02,1,0,0,17.9000,-62.8333
2309,NaN,Guyana,2020-03-12T05:53:03,1,1,0,5.0000,-58.7500
2310,NaN,Holy See,2020-03-10T19:13:21,1,0,0,41.9029,12.4534
2311,NaN,Jordan,2020-03-03T15:33:02,1,0,0,31.2400,36.5100
2312,NaN,Liechtenstein,2020-03-04T01:33:07,1,0,0,47.1400,9.5500
2313,NaN,Mongolia,2020-03-10T06:13:43,1,0,0,46.8625,103.8467
2314,NaN,Nepal,2020-03-10T08:33:03,1,0,1,28.3949,84.1240
2315,NaN,Reunion,2020-03-11T23:13:07,1,0,0,-21.1151,55.5364
2316,NaN,Togo,2020-03-07T02:13:09,1,0,0,8.6195,0.8248
2317,NaN,Turkey,2020-03-11T03:33:05,1,0,0,38.9637,35.2433
2318,Delaware,US,2020-03-11T23:13:06,1,0,0,39.3185,-75.5071
2319,Kansas,US,2020-03-10T03:13:17,1,0,0,38.5266,-96.7265
2320,Mississippi,US,2020-03-12T09:33:03,1,0,0,32.7416,-89.6787
2321,Missouri,US,2020-03-10T03:13:17,1,0,0,38.4561,-92.2884
2322,Montana,US,2020-03-11T23:13:06,1,0,0,46.9219,-110.4544
2323,North Dakota,US,2020-03-12T09:33:03,1,0,0,47.5289,-99.7840
2324,Wyoming,US,2020-03-12T03:13:09,1,0,0,42.7560,-107.3025
2325,NaN,Ukraine,2020-03-03T15:33:02,1,0,0,48.3794,31.1656
2326,Gibraltar,United Kingdom,2020-03-11T20:53:02,1,0,1,36.1408,-5.3536
2327,From Diamond Princess,Australia,2020-02-29T02:03:10,0,0,0,35.4437,139.6380
2328,Gansu,Mainland China,2020-03-11T02:18:28,0,0,0,36.0611,103.8343
2329,Hebei,Mainland China,2020-03-11T02:18:29,0,0,0,38.0428,114.5149
2330,Alaska,US,2020-03-10T02:33:04,0,0,0,61.3707,-152.4044
2331,Idaho,US,2020-03-10T02:33:04,0,0,0,44.2405,-114.4788
2332,Maine,US,2020-03-10T02:33:04,0,0,0,44.6939,-69.3819
2333,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
2334,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [27]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv'
response = requests.get(url)
response

In [28]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
2535,New Hampshire,US,2020-03-11T20:00:00,6,0,0,43.452492,-71.563896
2536,New Jersey,US,2020-03-11T20:00:00,29,1,0,40.298904,-74.521011
2537,New Mexico,US,2020-03-11T20:00:00,10,0,0,34.840515,-106.248482
2538,New York,US,2020-03-11T20:00:00,421,0,0,42.165726,-74.948051
2539,North Carolina,US,2020-03-11T20:00:00,17,0,0,35.630066,-79.806419
2540,North Dakota,US,2020-03-11T20:00:00,1,0,0,47.528912,-99.784012
2541,Ohio,US,2020-03-11T20:00:00,13,0,0,40.388783,-82.764915
2542,Oklahoma,US,2020-03-11T20:00:00,2,0,0,35.565342,-96.928917
2543,Oregon,US,2020-03-11T20:00:00,30,0,0,44.572021,-122.070938
2544,Pennsylvania,US,2020-03-11T20:00:00,41,0,0,40.590752,-77.209755
2545,Rhode Island,US,2020-03-11T20:00:00,14,0,0,41.680893,-71.511780
2546,South Carolina,US,2020-03-11T20:00:00,13,0,0,33.856892,-80.945007
2547,South Dakota,US,2020-03-11T20:00:00,8,1,0,44.299782,-99.438828
2548,Tennessee,US,2020-03-11T20:00:00,26,0,0,35.747845,-86.692345
2549,Texas,US,2020-03-11T20:00:00,43,0,0,31.054487,-97.563461
2550,Utah,US,2020-03-11T20:00:00,9,0,0,40.150032,-111.862434
2551,Vermont,US,2020-03-11T20:00:00,2,0,0,44.045876,-72.710686
2552,Virginia,US,2020-03-11T20:00:00,30,0,0,37.769337,-78.169968
2553,Washington,US,2020-03-11T20:00:00,568,37,1,47.400902,-121.490494
2554,West Virginia,US,2020-03-11T20:00:00,0,0,0,38.491226,-80.954453
2555,Wisconsin,US,2020-03-11T20:00:00,19,0,1,44.268543,-89.616508
2556,Wyoming,US,2020-03-11T20:00:00,1,0,0,42.755966,-107.302490
2557,NaN,Vietnam,2020-03-11T20:00:00,47,0,16,14.058300,108.277200
2558,NaN,Mongolia,2020-03-11T20:00:00,1,0,0,46.862500,103.846700
2559,NaN,Jamaica,2020-03-11T20:00:00,8,0,0,18.109600,-77.297500
2560,NaN,Afghanistan,2020-03-11T20:00:00,7,0,0,33.000000,65.000000
2561,NaN,Monaco,2020-03-11T20:00:00,2,0,0,43.733300,7.416700
2562,NaN,Liechtenstein,2020-03-11T20:00:00,1,0,0,47.140000,9.550000
2563,NaN,Guyana,2020-03-11T20:00:00,1,1,0,5.000000,-58.750000
2564,NaN,Taiwan*,2020-03-11T20:00:00,50,1,20,23.700000,121.000000

In [29]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-14-2020.csv'
response = requests.get(url)
response

In [30]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
2784,Tibet,China,2020-03-11T02:18:14,1,0,1,31.6927,88.0924
2785,NaN,Cote d'Ivoire,2020-03-13T22:22:02,1,0,0,7.5400,-5.5471
2786,NaN,Curacao,2020-03-14T16:15:18,1,0,0,12.1696,-68.9900
2787,NaN,Eswatini,2020-03-14T13:13:25,1,0,0,-26.5225,31.4659
2788,NaN,Ethiopia,2020-03-13T23:33:06,1,0,0,9.1450,40.4897
2789,Saint Barthelemy,France,2020-03-14T16:33:03,1,0,0,17.9000,-62.8333
2790,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
2791,NaN,Guadeloupe,2020-03-13T12:33:03,1,0,0,16.2650,-61.5510
2792,NaN,Guatemala,2020-03-14T01:33:03,1,0,0,15.7835,-90.2308
2793,NaN,Guernsey,2020-03-13T22:22:03,1,0,0,49.4500,-2.5800
2794,NaN,Guinea,2020-03-13T15:33:33,1,0,0,9.9456,-9.6966
2795,NaN,Guyana,2020-03-14T23:33:02,1,1,0,4.8604,-58.9302
2796,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
2797,NaN,Jordan,2020-03-14T12:53:07,1,0,1,30.5852,36.2384
2798,NaN,Kenya,2020-03-13T22:22:03,1,0,0,-0.0236,37.9062
2799,NaN,Mauritania,2020-03-14T12:53:07,1,0,0,21.0079,10.9408
2800,NaN,Mongolia,2020-03-13T22:22:02,1,0,0,46.8625,103.8467
2801,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
2802,NaN,Rwanda,2020-03-14T12:53:07,1,0,0,-1.9403,29.8739
2803,NaN,Saint Lucia,2020-03-14T16:15:18,1,0,0,13.9094,-60.9789
2804,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
2805,NaN,Sudan,2020-03-14T01:13:32,1,1,0,12.8628,30.2176
2806,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
2807,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
2808,North Dakota,US,2020-03-12T09:33:03,1,0,0,47.5289,-99.7840
2809,"Virgin Islands, U.S.",US,2020-03-14T16:15:18,1,0,0,18.3358,-64.8963
2810,Gibraltar,United Kingdom,2020-03-14T16:33:03,1,0,1,36.1408,-5.3536
2811,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
2812,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
2813,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [31]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-15-2020.csv'
response = requests.get(url)
response

In [32]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
3042,NaN,Curacao,2020-03-14T16:15:18,1,0,0,12.1696,-68.9900
3043,NaN,Equatorial Guinea,2020-03-15T06:41:54,1,0,0,1.5000,10.0000
3044,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
3045,NaN,Ethiopia,2020-03-13T23:33:06,1,0,0,9.1450,40.4897
3046,Mayotte,France,2020-03-14T20:53:03,1,0,0,-12.8275,45.1662
3047,Saint Barthelemy,France,2020-03-14T16:33:03,1,0,0,17.9000,-62.8333
3048,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
3049,NaN,Guadeloupe,2020-03-13T12:33:03,3,0,0,16.2650,-61.5510
3050,NaN,Guatemala,2020-03-14T01:33:03,1,0,0,15.7835,-90.2308
3051,NaN,Guernsey,2020-03-13T22:22:03,1,0,0,49.4500,-2.5800
3052,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
3053,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
3054,NaN,Kenya,2020-03-13T22:22:03,3,0,0,-0.0236,37.9062
3055,NaN,Mauritania,2020-03-15T18:20:19,1,0,0,21.0079,-10.9408
3056,NaN,Mongolia,2020-03-13T22:22:02,1,0,0,46.8625,103.8467
3057,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
3058,NaN,Rwanda,2020-03-15T06:41:54,1,0,0,-1.9403,29.8739
3059,NaN,Saint Lucia,2020-03-14T16:15:18,2,0,0,13.9094,-60.9789
3060,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
3061,NaN,Sudan,2020-03-14T01:13:32,1,1,0,12.8628,30.2176
3062,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
3063,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
3064,Alaska,US,2020-03-13T14:53:03,1,0,0,61.3707,-152.4044
3065,North Dakota,US,2020-03-12T09:33:03,1,0,0,47.5289,-99.7840
3066,"Virgin Islands, U.S.",US,2020-03-14T16:15:18,1,0,0,18.3358,-64.8963
3067,Gibraltar,United Kingdom,2020-03-14T16:33:03,1,0,1,36.1408,-5.3536
3068,NaN,Uzbekistan,2020-03-15T18:20:19,1,0,0,41.3775,64.5853
3069,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
3070,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
3071,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [33]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-16-2020.csv'
response = requests.get(url)
response

In [34]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
3314,NaN,Equatorial Guinea,2020-03-15T06:41:54,1,0,0,1.5000,10.0000
3315,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
3316,Mayotte,France,2020-03-16T14:38:45,1,0,0,-12.8431,45.1383
3317,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
3318,NaN,Greenland,2020-03-16T16:53:06,1,0,0,71.7069,-42.6043
3319,NaN,Guernsey,2020-03-13T22:22:03,1,0,0,49.4500,-2.5800
3320,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
3321,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
3322,NaN,Liberia,2020-03-16T14:38:46,1,0,0,6.4281,-9.4295
3323,NaN,Mauritania,2020-03-15T18:20:19,1,0,0,21.0079,-10.9408
3324,NaN,Mayotte,2020-03-16T14:38:45,1,0,0,-12.8275,45.1662
3325,NaN,Mongolia,2020-03-13T22:22:02,1,0,0,46.8625,103.8467
3326,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
3327,Curacao,Netherlands,2020-03-16T00:22:11,1,0,0,12.1696,-68.9900
3328,NaN,Republic of the Congo,2020-03-16T03:33:03,1,0,0,-1.4400,15.5560
3329,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
3330,NaN,Somalia,2020-03-16T14:38:46,1,0,0,5.1521,46.1996
3331,NaN,Sudan,2020-03-14T01:13:32,1,1,0,12.8628,30.2176
3332,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
3333,NaN,Tanzania,2020-03-16T14:38:45,1,0,0,-6.3690,34.8888
3334,NaN,The Bahamas,2020-03-16T03:33:03,1,0,0,24.2500,-76.0000
3335,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
3336,Alaska,US,2020-03-13T14:53:03,1,0,0,61.3707,-152.4044
3337,North Dakota,US,2020-03-12T09:33:03,1,0,0,47.5289,-99.7840
3338,Virgin Islands,US,2020-03-16T00:22:11,1,0,0,18.3358,-64.8963
3339,Cayman Islands,United Kingdom,2020-03-16T14:53:04,1,1,0,19.3133,-81.2546
3340,Gibraltar,United Kingdom,2020-03-14T16:33:03,1,0,1,36.1408,-5.3536
3341,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
3342,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
3343,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [35]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv'
response = requests.get(url)
response

In [36]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
3590,NaN,Central African Republic,2020-03-16T03:33:03,1,0,0,6.6111,20.9394
3591,Tibet,China,2020-03-11T02:18:14,1,0,1,31.6927,88.0924
3592,NaN,Congo (Brazzaville),2020-03-16T14:38:45,1,0,0,-0.2280,15.8277
3593,NaN,Equatorial Guinea,2020-03-15T06:41:54,1,0,0,1.5000,10.0000
3594,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
3595,Mayotte,France,2020-03-16T14:38:45,1,0,0,-12.8431,45.1383
3596,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
3597,NaN,Greenland,2020-03-16T16:53:06,1,0,0,71.7069,-42.6043
3598,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
3599,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
3600,NaN,Liberia,2020-03-17T12:13:16,1,0,0,6.4281,-9.4295
3601,NaN,Mauritania,2020-03-15T18:20:19,1,0,0,21.0079,-10.9408
3602,NaN,Mayotte,2020-03-16T14:38:45,1,0,0,-12.8275,45.1662
3603,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
3604,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
3605,NaN,Somalia,2020-03-16T14:38:46,1,0,0,5.1521,46.1996
3606,NaN,Sudan,2020-03-14T01:13:32,1,1,0,12.8628,30.2176
3607,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
3608,NaN,Tanzania,2020-03-17T01:33:03,1,0,0,-6.3690,34.8888
3609,NaN,The Bahamas,2020-03-16T03:33:03,1,0,0,24.2500,-76.0000
3610,NaN,The Gambia,2020-03-17T23:33:02,1,0,0,13.4667,-16.6000
3611,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
3612,West Virginia,US,2020-03-17T23:33:02,1,0,0,38.4912,-80.9545
3613,Cayman Islands,United Kingdom,2020-03-16T14:53:04,1,1,0,19.3133,-81.2546
3614,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
3615,NaN,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800
3616,NaN,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100
3617,NaN,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000
3618,NaN,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560
3619,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [37]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-18-2020.csv'
response = requests.get(url)
response

In [38]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
3874,NaN,Djibouti,2020-03-18T12:33:03,1,0,0,11.8251,42.5903
3875,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
3876,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
3877,NaN,"Gambia, The",2020-03-18T14:13:56,1,0,0,13.4432,-15.3101
3878,NaN,Greenland,2020-03-16T16:53:06,1,0,0,71.7069,-42.6043
3879,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
3880,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
3881,NaN,Mauritania,2020-03-15T18:20:19,1,0,0,21.0079,-10.9408
3882,NaN,Montenegro,2020-03-18T19:53:03,1,0,0,42.7087,19.3744
3883,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
3884,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
3885,NaN,Somalia,2020-03-18T00:53:03,1,0,0,5.1521,46.1996
3886,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
3887,NaN,The Bahamas,2020-03-16T03:33:03,1,0,0,24.2500,-76.0000
3888,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
3889,US,US,2020-03-18T19:33:03,1,0,106,37.0902,-95.7129
3890,West Virginia,US,2020-03-17T23:33:02,1,0,0,38.4912,-80.9545
3891,Cayman Islands,United Kingdom,2020-03-16T14:53:04,1,1,0,19.3133,-81.2546
3892,Montserrat,United Kingdom,2020-03-18T11:53:04,1,0,0,16.7425,-62.1874
3893,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
3894,French Guiana,France,2020-03-18T14:33:15,0,0,0,4.0000,-53.0000
3895,Guadeloupe,France,2020-03-18T14:33:15,0,0,0,16.2500,-61.5833
3896,Mayotte,France,2020-03-18T14:33:15,0,0,0,-12.8431,45.1383
3897,Reunion,France,2020-03-18T14:33:15,0,0,0,-21.1351,55.2471
3898,NaN,Guam,2020-03-18T19:14:33,0,0,0,13.4443,144.7937
3899,NaN,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800
3900,NaN,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100
3901,NaN,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000
3902,NaN,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560
3903,NaN,The Gambia,2020-03-18T14:13:56,0,0,0,13.4667,-16.6000

In [39]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-19-2020.csv'
response = requests.get(url)
response

In [40]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
4166,Tibet,China,2020-03-11T02:18:14,1,0,1,31.6927,88.0924
4167,NaN,Djibouti,2020-03-19T14:53:06,1,0,0,11.8251,42.5903
4168,NaN,El Salvador,2020-03-19T14:53:06,1,0,0,13.7942,-88.8965
4169,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
4170,NaN,Fiji,2020-03-19T14:53:06,1,0,0,-17.7134,178.0650
4171,NaN,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094
4172,NaN,"Gambia, The",2020-03-18T14:13:56,1,0,0,13.4432,-15.3101
4173,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
4174,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
4175,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
4176,NaN,Nicaragua,2020-03-19T08:33:08,1,0,0,12.8654,-85.2072
4177,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
4178,NaN,Somalia,2020-03-18T00:53:03,1,0,0,5.1521,46.1996
4179,NaN,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278
4180,NaN,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248
4181,US,US,2020-03-19T19:13:18,1,0,108,37.0902,-95.7129
4182,Montserrat,United Kingdom,2020-03-18T11:53:04,1,0,0,16.7425,-62.1874
4183,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
4184,French Guiana,France,2020-03-18T14:33:15,0,0,0,4.0000,-53.0000
4185,Guadeloupe,France,2020-03-18T14:33:15,0,0,0,16.2500,-61.5833
4186,Mayotte,France,2020-03-18T14:33:15,0,0,0,-12.8431,45.1383
4187,Reunion,France,2020-03-18T14:33:15,0,0,0,-21.1351,55.2471
4188,NaN,Greenland,2020-03-19T09:33:04,0,0,0,72.0000,-40.0000
4189,NaN,Guam,2020-03-18T19:14:33,0,0,0,13.4443,144.7937
4190,NaN,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800
4191,NaN,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100
4192,NaN,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000
4193,NaN,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560
4194,NaN,The Bahamas,2020-03-19T12:13:38,0,0,0,24.2500,-76.0000
4195,NaN,The Gambia,2020-03-18T14:13:56,0,0,0,13.4667,-16.6000

In [41]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv'
response = requests.get(url)
response

In [42]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
4465,NaN,El Salvador,2020-03-19T14:53:06,1,0,0,13.7942,-88.8965
4466,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
4467,NaN,Fiji,2020-03-19T14:53:06,1,0,0,-17.7134,178.0650
4468,NaN,"Gambia, The",2020-03-18T14:13:56,1,0,0,13.4432,-15.3101
4469,NaN,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966
4470,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
4471,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
4472,Sint Maarten,Netherlands,2020-03-20T21:13:30,1,0,0,18.0425,-63.0548
4473,NaN,Nicaragua,2020-03-19T08:33:08,1,0,0,12.8654,-85.2072
4474,NaN,Niger,2020-03-20T02:13:52,1,0,0,17.6078,8.0817
4475,NaN,Papua New Guinea,2020-03-20T18:13:12,1,0,0,-6.3150,143.9555
4476,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
4477,NaN,Somalia,2020-03-18T00:53:03,1,0,0,5.1521,46.1996
4478,US,US,2020-03-20T22:43:03,1,0,147,37.0902,-95.7129
4479,Isle of Man,United Kingdom,2020-03-20T15:13:21,1,0,0,54.2361,-4.5481
4480,Montserrat,United Kingdom,2020-03-18T11:53:04,1,0,0,16.7425,-62.1874
4481,NaN,Zimbabwe,2020-03-20T22:13:55,1,0,0,-20.0000,30.0000
4482,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
4483,French Guiana,France,2020-03-18T14:33:15,0,0,0,4.0000,-53.0000
4484,Guadeloupe,France,2020-03-18T14:33:15,0,0,0,16.2500,-61.5833
4485,Mayotte,France,2020-03-18T14:33:15,0,0,0,-12.8431,45.1383
4486,Reunion,France,2020-03-18T14:33:15,0,0,0,-21.1351,55.2471
4487,NaN,Greenland,2020-03-19T09:33:04,0,0,0,72.0000,-40.0000
4488,NaN,Guam,2020-03-18T19:14:33,0,0,0,13.4443,144.7937
4489,NaN,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800
4490,NaN,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100
4491,NaN,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000
4492,NaN,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560
4493,NaN,The Bahamas,2020-03-19T12:13:38,0,0,0,24.2500,-76.0000
4494,NaN,The Gambia,2020-03-18T14:13:56,0,0,0,13.4667,-16.6000

In [43]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-21-2020.csv'
response = requests.get(url)
response

In [44]:
df1 = pd.read_csv(url)
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.1832,120.0934
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.6104,111.7088
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.8257,117.2264
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.0000,53.0000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.6140,115.7221
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.3427,118.1498
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.4437,139.6380
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.9711,119.4550
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.0572,107.8740
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.6171,102.7103
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.8620,127.7615
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.1824,116.4142
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.2020,121.4491
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.0428,114.5149
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.0789,117.9874
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.0000,138.0000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.8298,108.7881
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.1917,108.8701
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.9740,101.4870
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.1959,109.7453
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.8154,106.8748
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.3054,117.3230
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.5777,112.2922
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.0000,2.0000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.0000,9.0000
...,...,...,...,...,...,...,...,...
4769,NaN,Djibouti,2020-03-19T14:53:06,1,0,0,11.8251,42.5903
4770,NaN,East Timor,2020-03-21T14:43:04,1,0,0,-8.5500,125.5600
4771,NaN,Eritrea,2020-03-21T21:13:30,1,0,0,15.1794,39.7823
4772,NaN,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659
4773,NaN,Fiji,2020-03-19T14:53:06,1,0,0,-17.7134,178.0650
4774,NaN,"Gambia, The",2020-03-18T14:13:56,1,0,0,13.4432,-15.3101
4775,NaN,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534
4776,NaN,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240
4777,Sint Maarten,Netherlands,2020-03-20T21:13:30,1,0,0,18.0425,-63.0548
4778,NaN,Niger,2020-03-20T02:13:52,1,0,0,17.6078,8.0817
4779,NaN,Papua New Guinea,2020-03-21T23:43:02,1,0,0,-6.3150,143.9555
4780,NaN,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872
4781,NaN,Somalia,2020-03-18T00:53:03,1,0,0,5.1521,46.1996
4782,US,US,2020-03-21T19:43:03,1,0,171,37.0902,-95.7129
4783,NaN,Uganda,2020-03-21T23:43:02,1,0,0,1.0000,32.0000
4784,Isle of Man,United Kingdom,2020-03-20T15:13:21,1,0,0,54.2361,-4.5481
4785,Montserrat,United Kingdom,2020-03-18T11:53:04,1,0,0,16.7425,-62.1874
4786,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380
4787,French Guiana,France,2020-03-18T14:33:15,0,0,0,4.0000,-53.0000
4788,Guadeloupe,France,2020-03-18T14:33:15,0,0,0,16.2500,-61.5833
4789,Mayotte,France,2020-03-18T14:33:15,0,0,0,-12.8431,45.1383
4790,Reunion,France,2020-03-18T14:33:15,0,0,0,-21.1351,55.2471
4791,NaN,Greenland,2020-03-19T09:33:04,0,0,0,72.0000,-40.0000
4792,NaN,Guam,2020-03-18T19:14:33,0,0,0,13.4443,144.7937
4793,NaN,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800
4794,NaN,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100
4795,NaN,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000
4796,NaN,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560
4797,NaN,The Bahamas,2020-03-19T12:13:38,0,0,0,24.2500,-76.0000
4798,NaN,The Gambia,2020-03-18T14:13:56,0,0,0,13.4667,-16.6000

Format Changes for columns.

In [45]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv'
response = requests.get(url)
response

In [46]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
8186,NaN,Benin,3/22/20 23:45,2,0,0,9.307700,2.315800
8187,Bermuda,United Kingdom,3/22/20 23:45,2,0,0,32.307800,-64.750500
8188,NaN,Bhutan,3/22/20 23:45,2,0,0,27.514200,90.433600
8189,NaN,Fiji,3/22/20 23:45,2,0,0,-17.713400,178.065000
8190,NaN,Guinea,3/22/20 23:45,2,0,0,9.945600,-9.696600
8191,NaN,Haiti,3/22/20 23:45,2,0,0,18.971200,-72.285200
8192,NaN,Mauritania,3/22/20 23:45,2,0,0,21.007900,10.940800
8193,NaN,Nicaragua,3/22/20 23:45,2,0,0,12.865416,-85.207229
8194,NaN,Niger,3/22/20 23:45,2,0,0,17.607789,8.081666
8195,NaN,Saint Lucia,3/22/20 23:45,2,0,0,13.909400,-60.978900
8196,NaN,Nepal,3/22/20 23:45,1,0,1,28.166700,84.250000
8197,NaN,Antigua and Barbuda,3/22/20 23:45,1,0,0,17.060800,-61.796400
8198,NaN,Chad,3/22/20 23:45,1,0,0,15.454200,18.732200
8199,NaN,Djibouti,3/22/20 23:45,1,0,0,11.825100,42.590300
8200,NaN,Dominica,3/22/20 23:45,1,0,0,15.415000,-61.371000
8201,NaN,Eritrea,3/22/20 23:45,1,0,0,15.179400,39.782300
8202,NaN,Gambia,3/22/20 23:45,1,0,0,13.443200,-15.310100
8203,NaN,Grenada,3/22/20 23:45,1,0,0,12.116500,-61.679000
8204,NaN,Holy See,3/22/20 23:45,1,0,0,41.902900,12.453400
8205,Montserrat,United Kingdom,3/22/20 23:45,1,0,0,16.742498,-62.187366
8206,NaN,Mozambique,3/22/20 23:45,1,0,0,-18.665695,35.529562
8207,NaN,Papua New Guinea,3/22/20 23:45,1,0,0,-6.314993,143.955550
8208,NaN,Saint Vincent and the Grenadines,3/22/20 23:45,1,0,0,12.984300,-61.287200
8209,Sint Maarten,Netherlands,3/22/20 23:45,1,0,0,18.042500,-63.054800
8210,NaN,Somalia,3/22/20 23:45,1,0,0,5.152149,46.199616
8211,NaN,Syria,3/22/20 23:45,1,0,0,34.802075,38.996815
8212,NaN,Timor-Leste,3/22/20 23:45,1,0,0,-8.874217,125.727539
8213,NaN,Uganda,3/22/20 23:45,1,0,0,1.373333,32.290275
8214,District of Columbia,US,3/22/20 23:45,102,2,0,38.904178,-77.016560
8215,Washington,US,3/22/20 23:45,1,2,0,46.451975,-117.545403

In [47]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv'
response = requests.get(url)
response

In [48]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
11601,NaN,Singapore,2020-03-23 23:19:21,509,2,152,1.283300,103.833300
11602,NaN,Slovakia,2020-03-23 23:19:21,186,0,7,48.669000,19.699000
11603,NaN,Slovenia,2020-03-23 23:19:21,442,3,0,46.151200,14.995500
11604,NaN,Somalia,2020-03-23 23:19:21,1,0,0,5.152149,46.199616
11605,NaN,South Africa,2020-03-23 23:19:21,402,0,4,-30.559500,22.937500
11606,NaN,Spain,2020-03-23 23:19:21,35136,2311,3355,40.463667,-3.749220
11607,NaN,Sri Lanka,2020-03-23 23:19:21,97,0,2,7.873054,80.771797
11608,NaN,Sudan,2020-03-23 23:19:21,2,1,0,12.862800,30.217600
11609,NaN,Suriname,2020-03-23 23:19:21,5,0,0,3.919300,-56.027800
11610,NaN,Sweden,2020-03-23 23:19:21,2046,25,16,60.128161,18.643501
11611,NaN,Switzerland,2020-03-23 23:19:21,8795,120,131,46.818200,8.227500
11612,NaN,Syria,2020-03-23 23:19:21,1,0,0,34.802075,38.996815
11613,NaN,Taiwan*,2020-03-23 06:45:13,195,2,28,23.700000,121.000000
11614,NaN,Tanzania,2020-03-23 23:19:21,12,0,0,-6.369028,34.888822
11615,NaN,Thailand,2020-03-23 23:19:21,721,1,52,15.870032,100.992541
11616,NaN,Timor-Leste,2020-03-23 23:19:21,1,0,0,-8.874217,125.727539
11617,NaN,Togo,2020-03-23 23:19:21,18,0,0,8.619500,0.824800
11618,NaN,Trinidad and Tobago,2020-03-23 23:19:21,51,0,0,10.691800,-61.222500
11619,NaN,Tunisia,2020-03-23 23:19:21,89,3,1,33.886917,9.537499
11620,NaN,Turkey,2020-03-23 23:19:21,1529,37,0,38.963700,35.243300
11621,NaN,Uganda,2020-03-23 23:19:21,9,0,0,1.373333,32.290275
11622,NaN,Ukraine,2020-03-23 23:19:21,73,3,1,48.379400,31.165600
11623,NaN,United Arab Emirates,2020-03-23 23:19:21,198,2,41,23.424076,53.847818
11624,NaN,United Kingdom,2020-03-23 23:19:21,6650,335,135,55.378100,-3.436000
11625,NaN,Uruguay,2020-03-23 23:19:21,158,0,0,-32.522800,-55.765800
11626,NaN,Uzbekistan,2020-03-23 23:19:21,46,0,0,41.377491,64.585262
11627,NaN,Venezuela,2020-03-23 23:19:21,77,0,15,6.423800,-66.589700
11628,NaN,Vietnam,2020-03-23 23:19:21,123,0,17,14.058324,108.277199
11629,NaN,Zambia,2020-03-23 23:19:21,3,0,0,-13.133897,27.849332
11630,NaN,Zimbabwe,2020-03-23 23:19:21,3,1,0,-19.015438,29.154857

In [49]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-24-2020.csv'
response = requests.get(url)
response

In [50]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
15018,NaN,Singapore,2020-03-24 23:37:15,558,2,156,1.283300,103.833300
15019,NaN,Slovakia,2020-03-24 23:37:15,204,0,7,48.669000,19.699000
15020,NaN,Slovenia,2020-03-24 23:37:15,480,4,3,46.151200,14.995500
15021,NaN,Somalia,2020-03-24 23:37:15,1,0,0,5.152149,46.199616
15022,NaN,South Africa,2020-03-24 23:37:15,554,0,4,-30.559500,22.937500
15023,NaN,Spain,2020-03-24 23:37:15,39885,2808,3794,40.463667,-3.749220
15024,NaN,Sri Lanka,2020-03-24 23:37:15,102,0,2,7.873054,80.771797
15025,NaN,Sudan,2020-03-24 23:37:15,3,1,0,12.862800,30.217600
15026,NaN,Suriname,2020-03-24 23:37:15,7,0,0,3.919300,-56.027800
15027,NaN,Sweden,2020-03-24 23:37:15,2286,36,16,60.128161,18.643501
15028,NaN,Switzerland,2020-03-24 23:37:15,9877,122,131,46.818200,8.227500
15029,NaN,Syria,2020-03-24 23:37:15,1,0,0,34.802075,38.996815
15030,NaN,Taiwan*,2020-03-24 07:38:21,215,2,29,23.700000,121.000000
15031,NaN,Tanzania,2020-03-24 23:37:15,12,0,0,-6.369028,34.888822
15032,NaN,Thailand,2020-03-24 23:37:15,827,4,52,15.870032,100.992541
15033,NaN,Timor-Leste,2020-03-24 23:37:15,1,0,0,-8.874217,125.727539
15034,NaN,Togo,2020-03-24 23:37:15,20,0,1,8.619500,0.824800
15035,NaN,Trinidad and Tobago,2020-03-24 23:37:15,57,0,0,10.691800,-61.222500
15036,NaN,Tunisia,2020-03-24 23:37:15,114,4,1,33.886917,9.537499
15037,NaN,Turkey,2020-03-24 23:37:15,1872,44,0,38.963700,35.243300
15038,NaN,Uganda,2020-03-24 23:37:15,9,0,0,1.373333,32.290275
15039,NaN,Ukraine,2020-03-24 23:37:15,97,3,1,48.379400,31.165600
15040,NaN,United Arab Emirates,2020-03-24 23:37:15,248,2,45,23.424076,53.847818
15041,NaN,United Kingdom,2020-03-24 23:37:15,8077,422,135,55.378100,-3.436000
15042,NaN,Uruguay,2020-03-24 23:37:15,162,0,0,-32.522800,-55.765800
15043,NaN,Uzbekistan,2020-03-24 23:37:15,50,0,0,41.377491,64.585262
15044,NaN,Venezuela,2020-03-24 23:37:15,84,0,15,6.423800,-66.589700
15045,NaN,Vietnam,2020-03-24 23:37:15,134,0,17,14.058324,108.277199
15046,NaN,Zambia,2020-03-24 23:37:15,3,0,0,-13.133897,27.849332
15047,NaN,Zimbabwe,2020-03-24 23:37:15,3,1,0,-19.015438,29.154857

In [51]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-25-2020.csv'
response = requests.get(url)
response

In [52]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
18438,NaN,Singapore,2020-03-25 23:33:04,631,2,160,1.283300,103.833300
18439,NaN,Slovakia,2020-03-25 23:33:04,216,0,7,48.669000,19.699000
18440,NaN,Slovenia,2020-03-25 23:33:04,528,5,10,46.151200,14.995500
18441,NaN,Somalia,2020-03-25 23:33:04,1,0,0,5.152149,46.199616
18442,NaN,South Africa,2020-03-25 23:33:04,709,0,12,-30.559500,22.937500
18443,NaN,Spain,2020-03-25 23:33:04,49515,3647,5367,40.463667,-3.749220
18444,NaN,Sri Lanka,2020-03-25 23:33:04,102,0,3,7.873054,80.771797
18445,NaN,Sudan,2020-03-25 23:33:04,3,1,0,12.862800,30.217600
18446,NaN,Suriname,2020-03-25 23:33:04,8,0,0,3.919300,-56.027800
18447,NaN,Sweden,2020-03-25 23:33:04,2526,62,16,60.128161,18.643501
18448,NaN,Switzerland,2020-03-25 23:33:04,10897,153,131,46.818200,8.227500
18449,NaN,Syria,2020-03-25 23:33:04,5,0,0,34.802075,38.996815
18450,NaN,Taiwan*,2020-03-25 08:02:14,235,2,29,23.700000,121.000000
18451,NaN,Tanzania,2020-03-25 23:33:04,12,0,0,-6.369028,34.888822
18452,NaN,Thailand,2020-03-25 23:33:04,934,4,70,15.870032,100.992541
18453,NaN,Timor-Leste,2020-03-25 23:33:04,1,0,0,-8.874217,125.727539
18454,NaN,Togo,2020-03-25 23:33:04,23,0,1,8.619500,0.824800
18455,NaN,Trinidad and Tobago,2020-03-25 23:33:04,60,1,0,10.691800,-61.222500
18456,NaN,Tunisia,2020-03-25 23:33:04,173,5,2,33.886917,9.537499
18457,NaN,Turkey,2020-03-25 23:33:04,2433,59,26,38.963700,35.243300
18458,NaN,Uganda,2020-03-25 23:33:04,14,0,0,1.373333,32.290275
18459,NaN,Ukraine,2020-03-25 23:33:04,145,5,1,48.379400,31.165600
18460,NaN,United Arab Emirates,2020-03-25 23:33:04,333,2,52,23.424076,53.847818
18461,NaN,United Kingdom,2020-03-25 23:33:04,9529,465,135,55.378100,-3.436000
18462,NaN,Uruguay,2020-03-25 23:33:04,189,0,0,-32.522800,-55.765800
18463,NaN,Uzbekistan,2020-03-25 23:33:04,60,0,0,41.377491,64.585262
18464,NaN,Venezuela,2020-03-25 23:33:04,91,0,15,6.423800,-66.589700
18465,NaN,Vietnam,2020-03-25 23:33:04,141,0,17,14.058324,108.277199
18466,NaN,Zambia,2020-03-25 23:33:04,12,0,0,-13.133897,27.849332
18467,NaN,Zimbabwe,2020-03-25 23:33:04,3,1,0,-19.015438,29.154857

In [53]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-26-2020.csv'
response = requests.get(url)
response

In [54]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
21859,NaN,Slovakia,2020-03-26 23:48:18,226,0,2,48.669000,19.699000
21860,NaN,Slovenia,2020-03-26 23:48:18,562,6,10,46.151200,14.995500
21861,NaN,Somalia,2020-03-26 23:48:18,2,0,0,5.152149,46.199616
21862,NaN,South Africa,2020-03-26 23:48:18,927,0,12,-30.559500,22.937500
21863,NaN,Spain,2020-03-26 23:48:18,57786,4365,7015,40.463667,-3.749220
21864,NaN,Sri Lanka,2020-03-26 23:48:18,106,0,7,7.873054,80.771797
21865,NaN,Sudan,2020-03-26 23:48:18,3,1,0,12.862800,30.217600
21866,NaN,Suriname,2020-03-26 23:48:18,8,0,0,3.919300,-56.027800
21867,NaN,Sweden,2020-03-26 23:48:18,2840,77,16,60.128161,18.643501
21868,NaN,Switzerland,2020-03-26 23:48:18,11811,191,131,46.818200,8.227500
21869,NaN,Syria,2020-03-26 23:48:18,5,0,0,34.802075,38.996815
21870,NaN,Taiwan*,2020-03-26 07:31:30,252,2,29,23.700000,121.000000
21871,NaN,Tanzania,2020-03-26 23:48:18,13,0,0,-6.369028,34.888822
21872,NaN,Thailand,2020-03-26 23:48:18,1045,4,88,15.870032,100.992541
21873,NaN,Timor-Leste,2020-03-26 23:48:18,1,0,0,-8.874217,125.727539
21874,NaN,Togo,2020-03-26 23:48:18,23,0,1,8.619500,0.824800
21875,NaN,Trinidad and Tobago,2020-03-26 23:48:18,65,1,0,10.691800,-61.222500
21876,NaN,Tunisia,2020-03-26 23:48:18,197,6,2,33.886917,9.537499
21877,NaN,Turkey,2020-03-26 23:48:18,3629,75,26,38.963700,35.243300
21878,NaN,Uganda,2020-03-26 23:48:18,14,0,0,1.373333,32.290275
21879,NaN,Ukraine,2020-03-26 23:48:18,196,5,1,48.379400,31.165600
21880,NaN,United Arab Emirates,2020-03-26 23:48:18,333,2,52,23.424076,53.847818
21881,NaN,United Kingdom,2020-03-26 23:48:18,11658,578,135,55.378100,-3.436000
21882,NaN,Uruguay,2020-03-26 23:48:18,217,0,0,-32.522800,-55.765800
21883,NaN,Uzbekistan,2020-03-26 23:48:18,75,0,0,41.377491,64.585262
21884,NaN,Venezuela,2020-03-26 23:48:18,107,0,15,6.423800,-66.589700
21885,NaN,Vietnam,2020-03-26 23:48:18,153,0,20,14.058324,108.277199
21886,NaN,West Bank and Gaza,2020-03-26 23:48:18,84,1,17,31.952200,35.233200
21887,NaN,Zambia,2020-03-26 23:48:18,16,0,0,-13.133897,27.849332
21888,NaN,Zimbabwe,2020-03-26 23:48:18,3,1,0,-19.015438,29.154857

In [55]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv'
response = requests.get(url)
response

In [56]:
df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
25288,NaN,Slovakia,2020-03-27 23:23:03,269,0,2,48.669000,19.699000
25289,NaN,Slovenia,2020-03-27 23:23:03,632,9,10,46.151200,14.995500
25290,NaN,Somalia,2020-03-27 23:23:03,3,0,0,5.152149,46.199616
25291,NaN,South Africa,2020-03-27 23:23:03,1170,1,31,-30.559500,22.937500
25292,NaN,Spain,2020-03-27 23:23:03,65719,5138,9357,40.463667,-3.749220
25293,NaN,Sri Lanka,2020-03-27 23:23:03,106,0,7,7.873054,80.771797
25294,NaN,Sudan,2020-03-27 23:23:03,3,1,0,12.862800,30.217600
25295,NaN,Suriname,2020-03-27 23:23:03,8,0,0,3.919300,-56.027800
25296,NaN,Sweden,2020-03-27 23:23:03,3069,105,16,60.128161,18.643501
25297,NaN,Switzerland,2020-03-27 23:23:03,12928,231,1530,46.818200,8.227500
25298,NaN,Syria,2020-03-27 23:23:03,5,0,0,34.802075,38.996815
25299,NaN,Taiwan*,2020-03-27 06:33:04,267,2,29,23.700000,121.000000
25300,NaN,Tanzania,2020-03-27 23:23:03,13,0,1,-6.369028,34.888822
25301,NaN,Thailand,2020-03-27 23:23:03,1136,5,97,15.870032,100.992541
25302,NaN,Timor-Leste,2020-03-27 23:23:03,1,0,0,-8.874217,125.727539
25303,NaN,Togo,2020-03-27 23:23:03,25,1,1,8.619500,0.824800
25304,NaN,Trinidad and Tobago,2020-03-27 23:23:03,66,2,1,10.691800,-61.222500
25305,NaN,Tunisia,2020-03-27 23:23:03,227,6,2,33.886917,9.537499
25306,NaN,Turkey,2020-03-27 23:23:03,5698,92,42,38.963700,35.243300
25307,NaN,Uganda,2020-03-27 23:23:03,23,0,0,1.373333,32.290275
25308,NaN,Ukraine,2020-03-27 23:23:03,310,5,5,48.379400,31.165600
25309,NaN,United Arab Emirates,2020-03-27 23:23:03,405,2,52,23.424076,53.847818
25310,NaN,United Kingdom,2020-03-27 23:23:03,14543,759,135,55.378100,-3.436000
25311,NaN,Uruguay,2020-03-27 23:23:03,238,0,0,-32.522800,-55.765800
25312,NaN,Uzbekistan,2020-03-27 23:23:03,88,1,5,41.377491,64.585262
25313,NaN,Venezuela,2020-03-27 23:23:03,107,1,31,6.423800,-66.589700
25314,NaN,Vietnam,2020-03-27 23:23:03,163,0,20,14.058324,108.277199
25315,NaN,West Bank and Gaza,2020-03-27 23:23:03,91,1,17,31.952200,35.233200
25316,NaN,Zambia,2020-03-27 23:23:03,22,0,0,-13.133897,27.849332
25317,NaN,Zimbabwe,2020-03-27 23:23:03,5,1,0,-19.015438,29.154857

In [57]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-28-2020.csv'
response = requests.get(url)
response

df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
28718,NaN,Slovakia,2020-03-28 23:05:25,292,0,2,48.669000,19.699000
28719,NaN,Slovenia,2020-03-28 23:05:25,684,9,10,46.151200,14.995500
28720,NaN,Somalia,2020-03-28 23:05:25,3,0,0,5.152149,46.199616
28721,NaN,South Africa,2020-03-28 23:05:25,1187,1,31,-30.559500,22.937500
28722,NaN,Spain,2020-03-28 23:05:25,73235,5982,12285,40.463667,-3.749220
28723,NaN,Sri Lanka,2020-03-28 23:05:25,113,1,9,7.873054,80.771797
28724,NaN,Sudan,2020-03-28 23:05:25,5,1,0,12.862800,30.217600
28725,NaN,Suriname,2020-03-28 23:05:25,8,0,0,3.919300,-56.027800
28726,NaN,Sweden,2020-03-28 23:05:25,3447,105,16,60.128161,18.643501
28727,NaN,Switzerland,2020-03-28 23:05:25,14076,264,1530,46.818200,8.227500
28728,NaN,Syria,2020-03-28 23:05:25,5,0,0,34.802075,38.996815
28729,NaN,Taiwan*,2020-03-28 06:58:13,283,2,30,23.700000,121.000000
28730,NaN,Tanzania,2020-03-28 23:05:25,14,0,1,-6.369028,34.888822
28731,NaN,Thailand,2020-03-28 23:05:25,1245,6,97,15.870032,100.992541
28732,NaN,Timor-Leste,2020-03-28 23:05:25,1,0,0,-8.874217,125.727539
28733,NaN,Togo,2020-03-28 23:05:25,25,1,1,8.619500,0.824800
28734,NaN,Trinidad and Tobago,2020-03-28 23:05:25,74,3,1,10.691800,-61.222500
28735,NaN,Tunisia,2020-03-28 23:05:25,278,8,2,33.886917,9.537499
28736,NaN,Turkey,2020-03-28 23:05:25,7402,108,70,38.963700,35.243300
28737,NaN,Uganda,2020-03-28 23:05:25,30,0,0,1.373333,32.290275
28738,NaN,Ukraine,2020-03-28 23:05:25,356,9,5,48.379400,31.165600
28739,NaN,United Arab Emirates,2020-03-28 23:05:25,468,2,52,23.424076,53.847818
28740,NaN,United Kingdom,2020-03-28 23:05:25,17089,1019,135,55.378100,-3.436000
28741,NaN,Uruguay,2020-03-28 23:05:25,274,0,0,-32.522800,-55.765800
28742,NaN,Uzbekistan,2020-03-28 23:05:25,104,2,5,41.377491,64.585262
28743,NaN,Venezuela,2020-03-28 23:05:25,119,2,39,6.423800,-66.589700
28744,NaN,Vietnam,2020-03-28 23:05:25,174,0,21,14.058324,108.277199
28745,NaN,West Bank and Gaza,2020-03-28 23:05:25,98,1,18,31.952200,35.233200
28746,NaN,Zambia,2020-03-28 23:05:25,28,0,0,-13.133897,27.849332
28747,NaN,Zimbabwe,2020-03-28 23:05:25,7,1,0,-19.015438,29.154857

In [58]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-29-2020.csv'
response = requests.get(url)
response

df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
32152,NaN,Slovakia,2020-03-29 23:08:13,314,0,2,48.669000,19.699000
32153,NaN,Slovenia,2020-03-29 23:08:13,730,11,10,46.151200,14.995500
32154,NaN,Somalia,2020-03-29 23:08:13,3,0,0,5.152149,46.199616
32155,NaN,South Africa,2020-03-29 23:08:13,1280,2,31,-30.559500,22.937500
32156,NaN,Spain,2020-03-29 23:08:13,80110,6803,14709,40.463667,-3.749220
32157,NaN,Sri Lanka,2020-03-29 23:08:13,117,1,11,7.873054,80.771797
32158,NaN,Sudan,2020-03-29 23:08:13,6,1,0,12.862800,30.217600
32159,NaN,Suriname,2020-03-29 23:08:13,8,0,0,3.919300,-56.027800
32160,NaN,Sweden,2020-03-29 23:08:13,3700,110,16,60.128161,18.643501
32161,NaN,Switzerland,2020-03-29 23:08:13,14829,300,1595,46.818200,8.227500
32162,NaN,Syria,2020-03-29 23:08:13,9,1,0,34.802075,38.996815
32163,NaN,Taiwan*,2020-03-29 08:04:48,298,2,30,23.700000,121.000000
32164,NaN,Tanzania,2020-03-29 23:08:13,14,0,1,-6.369028,34.888822
32165,NaN,Thailand,2020-03-29 23:08:13,1388,7,97,15.870032,100.992541
32166,NaN,Timor-Leste,2020-03-29 23:08:13,1,0,0,-8.874217,125.727539
32167,NaN,Togo,2020-03-29 23:08:13,25,1,1,8.619500,0.824800
32168,NaN,Trinidad and Tobago,2020-03-29 23:08:13,78,3,1,10.691800,-61.222500
32169,NaN,Tunisia,2020-03-29 23:08:13,312,8,2,33.886917,9.537499
32170,NaN,Turkey,2020-03-29 23:08:13,9217,131,105,38.963700,35.243300
32171,NaN,Uganda,2020-03-29 23:08:13,33,0,0,1.373333,32.290275
32172,NaN,Ukraine,2020-03-29 23:08:13,475,10,6,48.379400,31.165600
32173,NaN,United Arab Emirates,2020-03-29 23:08:13,570,3,58,23.424076,53.847818
32174,NaN,United Kingdom,2020-03-29 23:08:13,19522,1228,135,55.378100,-3.436000
32175,NaN,Uruguay,2020-03-29 23:08:13,304,1,0,-32.522800,-55.765800
32176,NaN,Uzbekistan,2020-03-29 23:08:13,144,2,7,41.377491,64.585262
32177,NaN,Venezuela,2020-03-29 23:08:13,119,2,39,6.423800,-66.589700
32178,NaN,Vietnam,2020-03-29 23:08:13,188,0,25,14.058324,108.277199
32179,NaN,West Bank and Gaza,2020-03-29 23:08:13,109,1,18,31.952200,35.233200
32180,NaN,Zambia,2020-03-29 23:08:13,29,0,0,-13.133897,27.849332
32181,NaN,Zimbabwe,2020-03-29 23:08:13,7,1,0,-19.015438,29.154857

In [ ]:
#df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/LatLongdata.csv', index = False)

In [ ]:
latlon = pd.read_csv('LatLongdata.csv')
latlon

In [ ]:
mask = latlon["Country/Region"] == "US"
df = latlon.loc[mask]
df

In [ ]:
#df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/USLatLon.csv', index = False)