In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/USLatLon.csv")
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,WA,US,3/1/20,9,1,1,47.606200,-122.332100
1,IL,US,3/1/20,3,0,2,41.878100,-87.629800
2,WA,US,3/1/20,2,0,0,48.033000,-121.833900
3,RI,US,3/1/20,1,0,0,41.824000,-71.412800
4,s),US,3/2/20,45,0,0,35.443700,139.638000
5,WA,US,3/2/20,14,5,1,47.548000,-121.983600
6,CA,US,3/2/20,9,0,1,37.354100,-121.955200
7,IL,US,3/2/20,4,0,2,41.737700,-87.697600
8,WA,US,3/2/20,4,1,0,48.033000,-121.833900
9,OR,US,3/2/20,2,0,0,45.505100,-122.675000
10,RI,US,3/2/20,2,0,0,41.824000,-71.412800
11,NH,US,3/2/20,1,0,0,43.908800,-71.826000
12,FL,US,3/2/20,1,0,0,27.990400,-82.301800
13,NY,US,3/2/20,1,0,0,40.712800,-74.006000
14,CA,US,3/2/20,1,0,0,39.091600,-120.803900
15,CA,US,3/2/20,1,0,0,37.563000,-122.325500
16,FL,US,3/2/20,1,0,0,27.336400,-82.530700
17,CA,US,3/2/20,1,0,0,38.578000,-122.988800
18,OR,US,3/2/20,1,0,0,45.775000,-118.760600
19,WA,US,3/3/20,21,6,1,47.548000,-121.983600
20,CA,US,3/3/20,11,0,1,37.354100,-121.955200
21,WA,US,3/3/20,6,1,0,48.033000,-121.833900
22,GA,US,3/3/20,2,0,0,33.803400,-84.396300
23,NH,US,3/3/20,2,0,0,43.908800,-71.826000
24,FL,US,3/3/20,2,0,0,27.990400,-82.301800
25,CA,US,3/3/20,2,0,0,37.563000,-122.325500
26,OR,US,3/3/20,2,0,0,45.547000,-123.138600
27,MA,US,3/3/20,1,0,0,42.176700,-71.144900
28,CA,US,3/3/20,1,0,0,37.871500,-122.273000
29,WI,US,3/3/20,1,0,1,43.073100,-89.401200
...,...,...,...,...,...,...,...,...
26115,SD,US,3/29/20,4,0,0,43.009245,-97.394676
26116,NY,US,3/29/20,0,0,0,42.635055,-77.103699
26117,AZ,US,3/29/20,12,0,0,34.599339,-112.553859
26118,MS,US,3/29/20,5,0,0,32.778904,-90.396561
26119,AR,US,3/29/20,0,0,0,35.002924,-93.411713
26120,MN,US,3/29/20,0,0,0,44.717102,-95.868425
26121,MT,US,3/29/20,26,0,0,45.939559,-108.269149
26122,TX,US,3/29/20,0,0,0,33.173202,-102.827643
26123,CA,US,3/29/20,16,1,0,38.682789,-121.901829
26124,ME,US,3/29/20,47,0,0,43.478084,-70.710524
26125,NE,US,3/29/20,0,0,0,40.872726,-97.597102
26126,PA,US,3/29/20,43,0,0,39.921009,-76.730401
26127,SC,US,3/29/20,36,0,0,34.972815,-81.180859
26128,VA,US,3/29/20,9,1,0,37.243748,-76.544128
26129,TX,US,3/29/20,1,0,0,33.176597,-98.687909
26130,CA,US,3/29/20,3,0,0,39.262559,-121.353564
26131,AK,US,3/29/20,0,0,0,65.508155,-151.390739
26132,AZ,US,3/29/20,5,0,0,32.768957,-113.906667
26133,CO,US,3/29/20,2,0,0,40.003468,-102.425867
26134,TX,US,3/29/20,0,0,0,27.001564,-99.169872
26135,TX,US,3/29/20,0,0,0,28.866172,-99.760508
26136,SD,US,3/29/20,0,0,0,44.978819,-101.665462
26137,American Samoa,US,3/29/20,0,0,0,-14.271000,-170.132000
26138,Diamond Princess,US,3/29/20,49,0,0,0.000000,0.000000
26139,Grand Princess,US,3/29/20,103,3,0,0.000000,0.000000
26140,Guam,US,3/29/20,56,1,0,13.444300,144.793700
26141,Northern Mariana Islands,US,3/29/20,0,0,0,15.097900,145.673900
26142,Puerto Rico,US,3/29/20,127,3,0,18.220800,-66.590100
26143,Recovered,US,3/29/20,0,0,2665,0.000000,0.000000
26144,Virgin Islands,US,3/29/20,0,0,0,18.335800,-64.896300

In [3]:
df.describe()

          Confirmed        Deaths     Recovered      Latitude     Longitude
count  26145.000000  26145.000000  26145.000000  26135.000000  26135.000000
mean      27.988793      0.431058      0.253930     38.102866    -91.346149
std      433.071484      7.037292     19.355158      6.454657     17.154938
min        0.000000      0.000000      0.000000    -14.271000   -170.132000
25%        0.000000      0.000000      0.000000     34.576921    -98.242066
50%        1.000000      0.000000      0.000000     38.357995    -90.194994
75%        4.000000      0.000000      0.000000     41.788692    -83.171407
max    33768.000000    678.000000   2665.000000     69.314792    145.673900

In [4]:
df["Confirmed"] = df["Confirmed"].fillna(0)
df["Deaths"] = df["Deaths"].fillna(0)
df["Recovered"] = df["Recovered"].fillna(0)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,WA,US,3/1/20,9,1,1,47.606200,-122.332100
1,IL,US,3/1/20,3,0,2,41.878100,-87.629800
2,WA,US,3/1/20,2,0,0,48.033000,-121.833900
3,RI,US,3/1/20,1,0,0,41.824000,-71.412800
4,s),US,3/2/20,45,0,0,35.443700,139.638000
5,WA,US,3/2/20,14,5,1,47.548000,-121.983600
6,CA,US,3/2/20,9,0,1,37.354100,-121.955200
7,IL,US,3/2/20,4,0,2,41.737700,-87.697600
8,WA,US,3/2/20,4,1,0,48.033000,-121.833900
9,OR,US,3/2/20,2,0,0,45.505100,-122.675000
10,RI,US,3/2/20,2,0,0,41.824000,-71.412800
11,NH,US,3/2/20,1,0,0,43.908800,-71.826000
12,FL,US,3/2/20,1,0,0,27.990400,-82.301800
13,NY,US,3/2/20,1,0,0,40.712800,-74.006000
14,CA,US,3/2/20,1,0,0,39.091600,-120.803900
15,CA,US,3/2/20,1,0,0,37.563000,-122.325500
16,FL,US,3/2/20,1,0,0,27.336400,-82.530700
17,CA,US,3/2/20,1,0,0,38.578000,-122.988800
18,OR,US,3/2/20,1,0,0,45.775000,-118.760600
19,WA,US,3/3/20,21,6,1,47.548000,-121.983600
20,CA,US,3/3/20,11,0,1,37.354100,-121.955200
21,WA,US,3/3/20,6,1,0,48.033000,-121.833900
22,GA,US,3/3/20,2,0,0,33.803400,-84.396300
23,NH,US,3/3/20,2,0,0,43.908800,-71.826000
24,FL,US,3/3/20,2,0,0,27.990400,-82.301800
25,CA,US,3/3/20,2,0,0,37.563000,-122.325500
26,OR,US,3/3/20,2,0,0,45.547000,-123.138600
27,MA,US,3/3/20,1,0,0,42.176700,-71.144900
28,CA,US,3/3/20,1,0,0,37.871500,-122.273000
29,WI,US,3/3/20,1,0,1,43.073100,-89.401200
...,...,...,...,...,...,...,...,...
26115,SD,US,3/29/20,4,0,0,43.009245,-97.394676
26116,NY,US,3/29/20,0,0,0,42.635055,-77.103699
26117,AZ,US,3/29/20,12,0,0,34.599339,-112.553859
26118,MS,US,3/29/20,5,0,0,32.778904,-90.396561
26119,AR,US,3/29/20,0,0,0,35.002924,-93.411713
26120,MN,US,3/29/20,0,0,0,44.717102,-95.868425
26121,MT,US,3/29/20,26,0,0,45.939559,-108.269149
26122,TX,US,3/29/20,0,0,0,33.173202,-102.827643
26123,CA,US,3/29/20,16,1,0,38.682789,-121.901829
26124,ME,US,3/29/20,47,0,0,43.478084,-70.710524
26125,NE,US,3/29/20,0,0,0,40.872726,-97.597102
26126,PA,US,3/29/20,43,0,0,39.921009,-76.730401
26127,SC,US,3/29/20,36,0,0,34.972815,-81.180859
26128,VA,US,3/29/20,9,1,0,37.243748,-76.544128
26129,TX,US,3/29/20,1,0,0,33.176597,-98.687909
26130,CA,US,3/29/20,3,0,0,39.262559,-121.353564
26131,AK,US,3/29/20,0,0,0,65.508155,-151.390739
26132,AZ,US,3/29/20,5,0,0,32.768957,-113.906667
26133,CO,US,3/29/20,2,0,0,40.003468,-102.425867
26134,TX,US,3/29/20,0,0,0,27.001564,-99.169872
26135,TX,US,3/29/20,0,0,0,28.866172,-99.760508
26136,SD,US,3/29/20,0,0,0,44.978819,-101.665462
26137,American Samoa,US,3/29/20,0,0,0,-14.271000,-170.132000
26138,Diamond Princess,US,3/29/20,49,0,0,0.000000,0.000000
26139,Grand Princess,US,3/29/20,103,3,0,0.000000,0.000000
26140,Guam,US,3/29/20,56,1,0,13.444300,144.793700
26141,Northern Mariana Islands,US,3/29/20,0,0,0,15.097900,145.673900
26142,Puerto Rico,US,3/29/20,127,3,0,18.220800,-66.590100
26143,Recovered,US,3/29/20,0,0,2665,0.000000,0.000000
26144,Virgin Islands,US,3/29/20,0,0,0,18.335800,-64.896300

In [5]:
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

dfUS = df[df["Province/State"].isin(abb)]
dfUS

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,WA,US,3/1/20,9,1,1,47.606200,-122.332100
1,IL,US,3/1/20,3,0,2,41.878100,-87.629800
2,WA,US,3/1/20,2,0,0,48.033000,-121.833900
3,RI,US,3/1/20,1,0,0,41.824000,-71.412800
5,WA,US,3/2/20,14,5,1,47.548000,-121.983600
6,CA,US,3/2/20,9,0,1,37.354100,-121.955200
7,IL,US,3/2/20,4,0,2,41.737700,-87.697600
8,WA,US,3/2/20,4,1,0,48.033000,-121.833900
9,OR,US,3/2/20,2,0,0,45.505100,-122.675000
10,RI,US,3/2/20,2,0,0,41.824000,-71.412800
11,NH,US,3/2/20,1,0,0,43.908800,-71.826000
12,FL,US,3/2/20,1,0,0,27.990400,-82.301800
13,NY,US,3/2/20,1,0,0,40.712800,-74.006000
14,CA,US,3/2/20,1,0,0,39.091600,-120.803900
15,CA,US,3/2/20,1,0,0,37.563000,-122.325500
16,FL,US,3/2/20,1,0,0,27.336400,-82.530700
17,CA,US,3/2/20,1,0,0,38.578000,-122.988800
18,OR,US,3/2/20,1,0,0,45.775000,-118.760600
19,WA,US,3/3/20,21,6,1,47.548000,-121.983600
20,CA,US,3/3/20,11,0,1,37.354100,-121.955200
21,WA,US,3/3/20,6,1,0,48.033000,-121.833900
22,GA,US,3/3/20,2,0,0,33.803400,-84.396300
23,NH,US,3/3/20,2,0,0,43.908800,-71.826000
24,FL,US,3/3/20,2,0,0,27.990400,-82.301800
25,CA,US,3/3/20,2,0,0,37.563000,-122.325500
26,OR,US,3/3/20,2,0,0,45.547000,-123.138600
27,MA,US,3/3/20,1,0,0,42.176700,-71.144900
28,CA,US,3/3/20,1,0,0,37.871500,-122.273000
29,WI,US,3/3/20,1,0,1,43.073100,-89.401200
30,AZ,US,3/3/20,1,0,0,33.291800,-112.429100
...,...,...,...,...,...,...,...,...
26107,WV,US,3/29/20,0,0,0,37.612327,-81.545111
26108,VA,US,3/29/20,1,0,0,36.915820,-81.078341
26109,NC,US,3/29/20,1,0,0,36.162226,-80.662394
26110,WA,US,3/29/20,140,2,0,46.457385,-120.738013
26111,AK,US,3/29/20,0,0,0,59.890981,-140.360145
26112,MS,US,3/29/20,3,0,0,34.028242,-89.707620
26113,OR,US,3/29/20,13,1,0,45.233304,-123.308696
26114,NC,US,3/29/20,0,0,0,35.900792,-82.312372
26115,SD,US,3/29/20,4,0,0,43.009245,-97.394676
26116,NY,US,3/29/20,0,0,0,42.635055,-77.103699
26117,AZ,US,3/29/20,12,0,0,34.599339,-112.553859
26118,MS,US,3/29/20,5,0,0,32.778904,-90.396561
26119,AR,US,3/29/20,0,0,0,35.002924,-93.411713
26120,MN,US,3/29/20,0,0,0,44.717102,-95.868425
26121,MT,US,3/29/20,26,0,0,45.939559,-108.269149
26122,TX,US,3/29/20,0,0,0,33.173202,-102.827643
26123,CA,US,3/29/20,16,1,0,38.682789,-121.901829
26124,ME,US,3/29/20,47,0,0,43.478084,-70.710524
26125,NE,US,3/29/20,0,0,0,40.872726,-97.597102
26126,PA,US,3/29/20,43,0,0,39.921009,-76.730401
26127,SC,US,3/29/20,36,0,0,34.972815,-81.180859
26128,VA,US,3/29/20,9,1,0,37.243748,-76.544128
26129,TX,US,3/29/20,1,0,0,33.176597,-98.687909
26130,CA,US,3/29/20,3,0,0,39.262559,-121.353564
26131,AK,US,3/29/20,0,0,0,65.508155,-151.390739
26132,AZ,US,3/29/20,5,0,0,32.768957,-113.906667
26133,CO,US,3/29/20,2,0,0,40.003468,-102.425867
26134,TX,US,3/29/20,0,0,0,27.001564,-99.169872
26135,TX,US,3/29/20,0,0,0,28.866172,-99.760508
26136,SD,US,3/29/20,0,0,0,44.978819,-101.665462

In [6]:
df.describe()

          Confirmed        Deaths     Recovered      Latitude     Longitude
count  26145.000000  26145.000000  26145.000000  26135.000000  26135.000000
mean      27.988793      0.431058      0.253930     38.102866    -91.346149
std      433.071484      7.037292     19.355158      6.454657     17.154938
min        0.000000      0.000000      0.000000    -14.271000   -170.132000
25%        0.000000      0.000000      0.000000     34.576921    -98.242066
50%        1.000000      0.000000      0.000000     38.357995    -90.194994
75%        4.000000      0.000000      0.000000     41.788692    -83.171407
max    33768.000000    678.000000   2665.000000     69.314792    145.673900

In [7]:
df.to_csv(r'/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CLEANUSLatLon.csv', index = False)