In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/LatLongdata.csv")
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
25288,NaN,Slovakia,2020-03-27 23:23:03,269,0,2,48.669000,19.699000
25289,NaN,Slovenia,2020-03-27 23:23:03,632,9,10,46.151200,14.995500
25290,NaN,Somalia,2020-03-27 23:23:03,3,0,0,5.152149,46.199616
25291,NaN,South Africa,2020-03-27 23:23:03,1170,1,31,-30.559500,22.937500
25292,NaN,Spain,2020-03-27 23:23:03,65719,5138,9357,40.463667,-3.749220
25293,NaN,Sri Lanka,2020-03-27 23:23:03,106,0,7,7.873054,80.771797
25294,NaN,Sudan,2020-03-27 23:23:03,3,1,0,12.862800,30.217600
25295,NaN,Suriname,2020-03-27 23:23:03,8,0,0,3.919300,-56.027800
25296,NaN,Sweden,2020-03-27 23:23:03,3069,105,16,60.128161,18.643501
25297,NaN,Switzerland,2020-03-27 23:23:03,12928,231,1530,46.818200,8.227500
25298,NaN,Syria,2020-03-27 23:23:03,5,0,0,34.802075,38.996815
25299,NaN,Taiwan*,2020-03-27 06:33:04,267,2,29,23.700000,121.000000
25300,NaN,Tanzania,2020-03-27 23:23:03,13,0,1,-6.369028,34.888822
25301,NaN,Thailand,2020-03-27 23:23:03,1136,5,97,15.870032,100.992541
25302,NaN,Timor-Leste,2020-03-27 23:23:03,1,0,0,-8.874217,125.727539
25303,NaN,Togo,2020-03-27 23:23:03,25,1,1,8.619500,0.824800
25304,NaN,Trinidad and Tobago,2020-03-27 23:23:03,66,2,1,10.691800,-61.222500
25305,NaN,Tunisia,2020-03-27 23:23:03,227,6,2,33.886917,9.537499
25306,NaN,Turkey,2020-03-27 23:23:03,5698,92,42,38.963700,35.243300
25307,NaN,Uganda,2020-03-27 23:23:03,23,0,0,1.373333,32.290275
25308,NaN,Ukraine,2020-03-27 23:23:03,310,5,5,48.379400,31.165600
25309,NaN,United Arab Emirates,2020-03-27 23:23:03,405,2,52,23.424076,53.847818
25310,NaN,United Kingdom,2020-03-27 23:23:03,14543,759,135,55.378100,-3.436000
25311,NaN,Uruguay,2020-03-27 23:23:03,238,0,0,-32.522800,-55.765800
25312,NaN,Uzbekistan,2020-03-27 23:23:03,88,1,5,41.377491,64.585262
25313,NaN,Venezuela,2020-03-27 23:23:03,107,1,31,6.423800,-66.589700
25314,NaN,Vietnam,2020-03-27 23:23:03,163,0,20,14.058324,108.277199
25315,NaN,West Bank and Gaza,2020-03-27 23:23:03,91,1,17,31.952200,35.233200
25316,NaN,Zambia,2020-03-27 23:23:03,22,0,0,-13.133897,27.849332
25317,NaN,Zimbabwe,2020-03-27 23:23:03,5,1,0,-19.015438,29.154857

In [3]:
df.describe()

          Confirmed        Deaths     Recovered      Latitude     Longitude
count  25318.000000  25318.000000  25318.000000  25305.000000  25305.000000
mean     232.004977      9.554744     82.021092     35.474867    -66.189888
std     2882.474295    175.463379   1706.991026     13.424841     61.669087
min        0.000000      0.000000      0.000000    -42.882100   -170.132000
25%        0.000000      0.000000      0.000000     33.079437    -96.670812
50%        1.000000      0.000000      0.000000     37.854472    -86.310294
75%       10.000000      0.000000      0.000000     41.902900    -76.606293
max    86498.000000   9134.000000  61732.000000     72.000000    178.065000

In [4]:
df["Confirmed"] = df["Confirmed"].fillna(0)
df["Deaths"] = df["Deaths"].fillna(0)
df["Recovered"] = df["Recovered"].fillna(0)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Zhejiang,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Hunan,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Anhui,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,NaN,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Jiangxi,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Shandong,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Diamond Princess cruise ship,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Jiangsu,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Chongqing,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Sichuan,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Heilongjiang,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Beijing,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Shanghai,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Hebei,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Fujian,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,NaN,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Guangxi,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Shaanxi,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Yunnan,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Hainan,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Guizhou,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Tianjin,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Shanxi,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,NaN,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,NaN,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...,...
25288,NaN,Slovakia,2020-03-27 23:23:03,269,0,2,48.669000,19.699000
25289,NaN,Slovenia,2020-03-27 23:23:03,632,9,10,46.151200,14.995500
25290,NaN,Somalia,2020-03-27 23:23:03,3,0,0,5.152149,46.199616
25291,NaN,South Africa,2020-03-27 23:23:03,1170,1,31,-30.559500,22.937500
25292,NaN,Spain,2020-03-27 23:23:03,65719,5138,9357,40.463667,-3.749220
25293,NaN,Sri Lanka,2020-03-27 23:23:03,106,0,7,7.873054,80.771797
25294,NaN,Sudan,2020-03-27 23:23:03,3,1,0,12.862800,30.217600
25295,NaN,Suriname,2020-03-27 23:23:03,8,0,0,3.919300,-56.027800
25296,NaN,Sweden,2020-03-27 23:23:03,3069,105,16,60.128161,18.643501
25297,NaN,Switzerland,2020-03-27 23:23:03,12928,231,1530,46.818200,8.227500
25298,NaN,Syria,2020-03-27 23:23:03,5,0,0,34.802075,38.996815
25299,NaN,Taiwan*,2020-03-27 06:33:04,267,2,29,23.700000,121.000000
25300,NaN,Tanzania,2020-03-27 23:23:03,13,0,1,-6.369028,34.888822
25301,NaN,Thailand,2020-03-27 23:23:03,1136,5,97,15.870032,100.992541
25302,NaN,Timor-Leste,2020-03-27 23:23:03,1,0,0,-8.874217,125.727539
25303,NaN,Togo,2020-03-27 23:23:03,25,1,1,8.619500,0.824800
25304,NaN,Trinidad and Tobago,2020-03-27 23:23:03,66,2,1,10.691800,-61.222500
25305,NaN,Tunisia,2020-03-27 23:23:03,227,6,2,33.886917,9.537499
25306,NaN,Turkey,2020-03-27 23:23:03,5698,92,42,38.963700,35.243300
25307,NaN,Uganda,2020-03-27 23:23:03,23,0,0,1.373333,32.290275
25308,NaN,Ukraine,2020-03-27 23:23:03,310,5,5,48.379400,31.165600
25309,NaN,United Arab Emirates,2020-03-27 23:23:03,405,2,52,23.424076,53.847818
25310,NaN,United Kingdom,2020-03-27 23:23:03,14543,759,135,55.378100,-3.436000
25311,NaN,Uruguay,2020-03-27 23:23:03,238,0,0,-32.522800,-55.765800
25312,NaN,Uzbekistan,2020-03-27 23:23:03,88,1,5,41.377491,64.585262
25313,NaN,Venezuela,2020-03-27 23:23:03,107,1,31,6.423800,-66.589700
25314,NaN,Vietnam,2020-03-27 23:23:03,163,0,20,14.058324,108.277199
25315,NaN,West Bank and Gaza,2020-03-27 23:23:03,91,1,17,31.952200,35.233200
25316,NaN,Zambia,2020-03-27 23:23:03,22,0,0,-13.133897,27.849332
25317,NaN,Zimbabwe,2020-03-27 23:23:03,5,1,0,-19.015438,29.154857

In [5]:
df = df[["Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]
df

,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
11,Others,2020-02-29T01:43:02,705,6,10,35.443700,139.638000
12,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
20,Japan,2020-03-01T23:33:03,256,6,32,36.000000,138.000000
21,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
28,France,2020-03-01T20:43:02,130,2,12,47.000000,2.000000
29,Germany,2020-03-01T23:23:02,130,0,16,51.000000,9.000000
...,...,...,...,...,...,...,...
25288,Slovakia,2020-03-27 23:23:03,269,0,2,48.669000,19.699000
25289,Slovenia,2020-03-27 23:23:03,632,9,10,46.151200,14.995500
25290,Somalia,2020-03-27 23:23:03,3,0,0,5.152149,46.199616
25291,South Africa,2020-03-27 23:23:03,1170,1,31,-30.559500,22.937500
25292,Spain,2020-03-27 23:23:03,65719,5138,9357,40.463667,-3.749220
25293,Sri Lanka,2020-03-27 23:23:03,106,0,7,7.873054,80.771797
25294,Sudan,2020-03-27 23:23:03,3,1,0,12.862800,30.217600
25295,Suriname,2020-03-27 23:23:03,8,0,0,3.919300,-56.027800
25296,Sweden,2020-03-27 23:23:03,3069,105,16,60.128161,18.643501
25297,Switzerland,2020-03-27 23:23:03,12928,231,1530,46.818200,8.227500
25298,Syria,2020-03-27 23:23:03,5,0,0,34.802075,38.996815
25299,Taiwan*,2020-03-27 06:33:04,267,2,29,23.700000,121.000000
25300,Tanzania,2020-03-27 23:23:03,13,0,1,-6.369028,34.888822
25301,Thailand,2020-03-27 23:23:03,1136,5,97,15.870032,100.992541
25302,Timor-Leste,2020-03-27 23:23:03,1,0,0,-8.874217,125.727539
25303,Togo,2020-03-27 23:23:03,25,1,1,8.619500,0.824800
25304,Trinidad and Tobago,2020-03-27 23:23:03,66,2,1,10.691800,-61.222500
25305,Tunisia,2020-03-27 23:23:03,227,6,2,33.886917,9.537499
25306,Turkey,2020-03-27 23:23:03,5698,92,42,38.963700,35.243300
25307,Uganda,2020-03-27 23:23:03,23,0,0,1.373333,32.290275
25308,Ukraine,2020-03-27 23:23:03,310,5,5,48.379400,31.165600
25309,United Arab Emirates,2020-03-27 23:23:03,405,2,52,23.424076,53.847818
25310,United Kingdom,2020-03-27 23:23:03,14543,759,135,55.378100,-3.436000
25311,Uruguay,2020-03-27 23:23:03,238,0,0,-32.522800,-55.765800
25312,Uzbekistan,2020-03-27 23:23:03,88,1,5,41.377491,64.585262
25313,Venezuela,2020-03-27 23:23:03,107,1,31,6.423800,-66.589700
25314,Vietnam,2020-03-27 23:23:03,163,0,20,14.058324,108.277199
25315,West Bank and Gaza,2020-03-27 23:23:03,91,1,17,31.952200,35.233200
25316,Zambia,2020-03-27 23:23:03,22,0,0,-13.133897,27.849332
25317,Zimbabwe,2020-03-27 23:23:03,5,1,0,-19.015438,29.154857

In [6]:
countries = ['US', 'Mainland China', 'Italy', 'New Zealand', 'South Korea', 'UK', 'Iran', 'Singapore', 'India', 'Peru']
df = df.loc[df['Country/Region'].isin(countries)]
df

,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.975600,112.270700
1,South Korea,2020-03-01T23:43:03,3736,17,30,36.000000,128.000000
2,Italy,2020-03-01T23:23:02,1694,34,83,43.000000,12.000000
3,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.341700,113.424400
4,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.882000,113.614000
5,Mainland China,2020-03-01T10:13:33,1205,1,1046,29.183200,120.093400
6,Mainland China,2020-03-01T10:03:03,1018,4,866,27.610400,111.708800
7,Mainland China,2020-03-01T10:03:03,990,6,873,31.825700,117.226400
8,Iran,2020-03-01T15:33:03,978,54,175,32.000000,53.000000
9,Mainland China,2020-03-01T01:13:10,935,1,831,27.614000,115.722100
10,Mainland China,2020-03-01T11:33:03,758,6,443,36.342700,118.149800
12,Mainland China,2020-03-01T10:03:03,631,0,536,32.971100,119.455000
13,Mainland China,2020-03-01T23:13:08,576,6,450,30.057200,107.874000
14,Mainland China,2020-03-01T11:43:02,538,3,365,30.617100,102.710300
15,Mainland China,2020-03-01T11:33:03,480,13,342,47.862000,127.761500
16,Mainland China,2020-03-01T02:53:03,413,8,276,40.182400,116.414200
17,Mainland China,2020-03-01T07:13:07,337,3,290,31.202000,121.449100
18,Mainland China,2020-03-01T14:13:18,318,6,294,38.042800,114.514900
19,Mainland China,2020-03-01T09:43:03,296,1,247,26.078900,117.987400
21,Mainland China,2020-03-01T09:43:03,252,2,181,23.829800,108.788100
22,Mainland China,2020-03-01T09:43:03,245,1,208,35.191700,108.870100
23,Mainland China,2020-03-01T07:13:07,174,2,163,24.974000,101.487000
24,Mainland China,2020-03-01T10:13:38,168,5,149,19.195900,109.745300
25,Mainland China,2020-02-27T00:43:02,146,2,112,26.815400,106.874800
26,Mainland China,2020-03-01T12:43:02,136,3,111,39.305400,117.323000
27,Mainland China,2020-03-01T23:13:08,133,0,116,37.577700,112.292200
30,Mainland China,2020-03-01T12:23:06,122,1,103,41.295600,122.608500
31,Singapore,2020-03-01T23:23:02,106,0,72,1.283300,103.833300
33,Mainland China,2020-03-01T09:43:03,93,1,78,43.666100,126.192300
34,Mainland China,2020-03-01T14:33:17,91,2,84,36.061100,103.834300
...,...,...,...,...,...,...,...
25046,US,2020-03-27 22:14:55,20,0,0,45.939559,-108.269149
25047,US,2020-03-27 22:14:55,1,0,0,33.173202,-102.827643
25048,US,2020-03-27 22:14:55,13,1,0,38.682789,-121.901829
25049,US,2020-03-27 22:14:55,33,0,0,43.478084,-70.710524
25050,US,2020-03-27 22:14:55,0,0,0,40.872726,-97.597102
25051,US,2020-03-27 22:14:55,30,0,0,39.921009,-76.730401
25052,US,2020-03-27 22:14:55,19,0,0,34.972815,-81.180859
25053,US,2020-03-27 22:14:55,9,1,0,37.243748,-76.544128
25054,US,2020-03-27 22:14:55,1,0,0,33.176597,-98.687909
25055,US,2020-03-27 22:14:55,3,0,0,39.262559,-121.353564
25056,US,2020-03-27 22:14:55,0,0,0,65.508155,-151.390739
25057,US,2020-03-27 22:14:55,4,0,0,32.768957,-113.906667
25058,US,2020-03-27 22:14:55,2,0,0,40.003468,-102.425867
25059,US,2020-03-27 22:14:55,0,0,0,27.001564,-99.169872
25060,US,2020-03-27 22:14:55,0,0,0,28.866172,-99.760508
25061,US,2020-03-27 22:14:55,0,0,0,44.978819,-101.665462
25063,US,2020-03-27 22:14:55,0,0,0,-14.271000,-170.132000
25075,US,2020-03-27 22:14:55,49,0,0,0.000000,0.000000
25083,US,2020-03-27 22:14:55,28,3,0,0.000000,0.000000
25086,US,2020-03-27 22:14:55,51,1,0,13.444300,144.793700
25113,US,2020-03-27 22:14:55,0,0,0,15.097900,145.673900
25119,US,2020-03-27 22:14:55,79,3,0,18.220800,-66.590100
25124,US,2020-03-27 22:14:55,0,0,869,0.000000,0.000000
25140,US,2020-03-27 22:14:55,19,0,0,18.335800,-64.896300
25219,India,2020-03-27 23:23:03,887,20,73,20.593684,78.962880
25221,Iran,2020-03-27 23:23:03,32332,2378,11133,32.427908,53.688046
25225,Italy,2020-03-27 23:23:03,86498,9134,10950,41.871940,12.567380
25260,New Zealand,2020-03-27 23:23:03,368,0,37,-40.900600,174.886000
25271,Peru,2020-03-27 23:23:03,635,11,16,-9.190000,-75.015200
25287,Singapore,2020-03-27 23:23:03,732,2,183,1.283300,103.833300

In [7]:
df.to_csv(r'/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CLEANLatLonData.csv', index = False)