In [1]:
import requests
import pandas as pd

dates = ['01-22', '01-23', '01-24', '01-25', '01-26', '01-27', '01-28', '01-29', '01-30', '01-31']

df = pd.DataFrame()

for x in range(len(dates)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates[x] + '-2020.csv'
    response = requests.get(str(url))
        
    df1 = pd.read_csv(url)
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[0:7] + "20")
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
    abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

    for x in range(51):
        df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
        df1["Province/State"] = df1["Province/State"].replace("Chicago", "IL")    
    df = df.append(df1, ignore_index = True)

#df

In [2]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-01-2020.csv'
response = requests.get(url)

df1 = pd.read_csv(url)
df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[0:1] + "/0" + x[2:6] + "20")
mask = df1['Last Update'] == "02/01/2020"
df1 = df1.loc[mask]

df1["Province/State"] = df1["Province/State"].fillna("none") 
df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])
df = df.append(df1, ignore_index = True)
#df

In [3]:
dates2 = ['02-02', '02-03', '02-04', '02-05', '02-06', '02-07', '02-08', '02-09', '02-10', '02-11', '02-12',
        '02-13', '02-14', '02-15', '02-16', '02-17', '02-18', '02-19', '02-20', '02-21', '02-22', '02-23',
        '02-24', '02-25', '02-26', '02-27', '02-28', '02-29']

for x in range(len(dates2)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates2[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:10] + "/" + "2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]

    df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
    df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
    df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")

    df1["Province/State"] = df1["Province/State"].fillna("none") 
    df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

    df = df.append(df1, ignore_index = True)

#df

In [4]:
dates3 = ['03-01', '03-02', '03-03', '03-04', '03-05', '03-06', '03-07', '03-08', '03-09']

for x in range(len(dates3)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates3[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:7] + "/0" + x[9] + "/" + "2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]

    df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
    df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
    df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")
    df1["Province/State"] = df1["Province/State"].replace("Washington, D.C.", "DC")

    df1["Province/State"] = df1["Province/State"].fillna("none") 
    df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

    df = df.append(df1, ignore_index = True)
    
#df

In [5]:
dates4 = ['03-10', '03-11', '03-12', '03-13', '03-14', '03-15', '03-16', '03-17', 
        '03-18', '03-19', '03-20', '03-21']

for x in range(len(dates4)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates4[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1 = df1[["Province/State", "Country/Region",  "Last Update", "Confirmed", "Deaths", "Recovered"]]
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:10] + "/" + "2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
    abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

    for x in range(51):
        df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
    df = df.append(df1, ignore_index = True)
    
#df

In [6]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv'
response = requests.get(url)

df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x :"0" + x[0:7] + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
#df

In [7]:
dates5 = ['03-23', '03-24', '03-25', '03-26', '03-27', '03-28', 
        '03-29', '03-30', '03-31', '04-01', '04-02']
         #'04-03', '04-04', '04-05', '04-06', '04-07', '04-08', '04-09', '04-10', '04-11', '04-12', '04-13',
         #'04-14', '04-15','04-16', '04-17', '04-18', '04-19', '04-20', '04-21']

for x in range(len(dates5)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates5[x] + '-2020.csv'
    response = requests.get(url)
    
    df1 = pd.read_csv(url)
    df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update"})
    df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered"]]

    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:10] + "/2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
    abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

    for x in range(51):
        df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

    df = df.append(df1, ignore_index = True)
    
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,01/22/2020,1.0,NaN,NaN
1,Beijing,Mainland China,01/22/2020,14.0,NaN,NaN
2,Chongqing,Mainland China,01/22/2020,6.0,NaN,NaN
3,Fujian,Mainland China,01/22/2020,1.0,NaN,NaN
4,Gansu,Mainland China,01/22/2020,NaN,NaN,NaN
5,Guangdong,Mainland China,01/22/2020,26.0,NaN,NaN
6,Guangxi,Mainland China,01/22/2020,2.0,NaN,NaN
7,Guizhou,Mainland China,01/22/2020,1.0,NaN,NaN
8,Hainan,Mainland China,01/22/2020,4.0,NaN,NaN
9,Hebei,Mainland China,01/22/2020,1.0,NaN,NaN
10,Heilongjiang,Mainland China,01/22/2020,NaN,NaN,NaN
11,Henan,Mainland China,01/22/2020,5.0,NaN,NaN
12,Hong Kong,Hong Kong,01/22/2020,NaN,NaN,NaN
13,Hubei,Mainland China,01/22/2020,444.0,17.0,28.0
14,Hunan,Mainland China,01/22/2020,4.0,NaN,NaN
15,Inner Mongolia,Mainland China,01/22/2020,NaN,NaN,NaN
16,Jiangsu,Mainland China,01/22/2020,1.0,NaN,NaN
17,Jiangxi,Mainland China,01/22/2020,2.0,NaN,NaN
18,Jilin,Mainland China,01/22/2020,NaN,NaN,NaN
19,Liaoning,Mainland China,01/22/2020,2.0,NaN,NaN
20,Macau,Macau,01/22/2020,1.0,NaN,NaN
21,Ningxia,Mainland China,01/22/2020,1.0,NaN,NaN
22,Qinghai,Mainland China,01/22/2020,NaN,NaN,NaN
23,Shaanxi,Mainland China,01/22/2020,NaN,NaN,NaN
24,Shandong,Mainland China,01/22/2020,2.0,NaN,NaN
25,Shanghai,Mainland China,01/22/2020,9.0,NaN,NaN
26,Shanxi,Mainland China,01/22/2020,1.0,NaN,NaN
27,Sichuan,Mainland China,01/22/2020,5.0,NaN,NaN
28,Taiwan,Taiwan,01/22/2020,1.0,NaN,NaN
29,Tianjin,Mainland China,01/22/2020,4.0,NaN,NaN
...,...,...,...,...,...,...
42709,NaN,Slovakia,0 23:/2020,426.0,1.0,5.0
42710,NaN,Slovenia,0 23:/2020,897.0,17.0,70.0
42711,NaN,Somalia,0 23:/2020,5.0,0.0,1.0
42712,NaN,South Africa,0 23:/2020,1462.0,5.0,50.0
42713,NaN,Spain,0 23:/2020,112065.0,10348.0,26743.0
42714,NaN,Sri Lanka,0 23:/2020,151.0,4.0,21.0
42715,NaN,Sudan,0 23:/2020,8.0,2.0,2.0
42716,NaN,Suriname,0 23:/2020,10.0,0.0,0.0
42717,NaN,Sweden,0 23:/2020,5568.0,308.0,103.0
42718,NaN,Switzerland,0 23:/2020,18827.0,536.0,4013.0
42719,NaN,Syria,0 23:/2020,16.0,2.0,0.0
42720,NaN,Tanzania,0 23:/2020,20.0,1.0,2.0
42721,NaN,Thailand,0 23:/2020,1875.0,15.0,505.0
42722,NaN,Timor-Leste,0 23:/2020,1.0,0.0,0.0
42723,NaN,Togo,0 23:/2020,39.0,2.0,17.0
42724,NaN,Trinidad and Tobago,0 23:/2020,94.0,5.0,1.0
42725,NaN,Tunisia,0 23:/2020,455.0,14.0,5.0
42726,NaN,Turkey,0 23:/2020,18135.0,356.0,415.0
42727,NaN,Uganda,0 23:/2020,45.0,0.0,0.0
42728,NaN,Ukraine,0 23:/2020,897.0,22.0,19.0
42729,NaN,United Arab Emirates,0 23:/2020,1024.0,8.0,96.0
42730,NaN,United Kingdom,0 23:/2020,33718.0,2921.0,135.0
42731,NaN,Uruguay,0 23:/2020,350.0,4.0,62.0
42732,NaN,Uzbekistan,0 23:/2020,205.0,2.0,25.0
42733,NaN,Venezuela,0 23:/2020,146.0,5.0,43.0
42734,NaN,Vietnam,0 23:/2020,233.0,0.0,75.0
42735,NaN,West Bank and Gaza,0 23:/2020,161.0,1.0,18.0
42736,NaN,Zambia,0 23:/2020,39.0,1.0,0.0
42737,NaN,Zimbabwe,0 23:/2020,9.0,1.0,0.0
42738,WY,US,0 23:/2020,0.0,0.0,0.0

In [8]:
df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/CDRdata.csv', index = False)

In [9]:
import requests
import pandas as pd

dates = ['03-01', '03-02', '03-03', '03-04', '03-05', '03-06', '03-07', '03-08', '03-09']

df = pd.DataFrame()

for x in range(len(dates)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:7] + "/0" + x[9] + "/" + "2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]

    df1["Province/State"] = df1["Province/State"].replace("Omaha, NE (From Diamond Princess)", "NE")
    df1["Province/State"] = df1["Province/State"].replace("Travis, CA (From Diamond Princess)", "CA")
    df1["Province/State"] = df1["Province/State"].replace("Lackland, TX (From Diamond Princess)", "TX")
    df1["Province/State"] = df1["Province/State"].replace("Washington, D.C.", "DC")

    df1["Province/State"] = df1["Province/State"].fillna("none") 
    df1['Province/State'] = df1['Province/State'].apply(lambda x : x[-2:])

    df = df.append(df1, ignore_index = True)
    
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,ei,Mainland China,03/01/2020,66907,2761,31536,30.9756,112.2707
1,ne,South Korea,03/01/2020,3736,17,30,36.0000,128.0000
2,ne,Italy,03/01/2020,1694,34,83,43.0000,12.0000
3,ng,Mainland China,03/01/2020,1349,7,1016,23.3417,113.4244
4,an,Mainland China,03/01/2020,1272,22,1198,33.8820,113.6140
5,ng,Mainland China,03/01/2020,1205,1,1046,29.1832,120.0934
6,an,Mainland China,03/01/2020,1018,4,866,27.6104,111.7088
7,ui,Mainland China,03/01/2020,990,6,873,31.8257,117.2264
8,ne,Iran,03/01/2020,978,54,175,32.0000,53.0000
9,xi,Mainland China,03/01/2020,935,1,831,27.6140,115.7221
10,ng,Mainland China,03/01/2020,758,6,443,36.3427,118.1498
11,su,Mainland China,03/01/2020,631,0,536,32.9711,119.4550
12,ng,Mainland China,03/01/2020,576,6,450,30.0572,107.8740
13,an,Mainland China,03/01/2020,538,3,365,30.6171,102.7103
14,ng,Mainland China,03/01/2020,480,13,342,47.8620,127.7615
15,ng,Mainland China,03/01/2020,413,8,276,40.1824,116.4142
16,ai,Mainland China,03/01/2020,337,3,290,31.2020,121.4491
17,ei,Mainland China,03/01/2020,318,6,294,38.0428,114.5149
18,an,Mainland China,03/01/2020,296,1,247,26.0789,117.9874
19,ne,Japan,03/01/2020,256,6,32,36.0000,138.0000
20,xi,Mainland China,03/01/2020,252,2,181,23.8298,108.7881
21,xi,Mainland China,03/01/2020,245,1,208,35.1917,108.8701
22,an,Mainland China,03/01/2020,174,2,163,24.9740,101.4870
23,an,Mainland China,03/01/2020,168,5,149,19.1959,109.7453
24,in,Mainland China,03/01/2020,136,3,111,39.3054,117.3230
25,xi,Mainland China,03/01/2020,133,0,116,37.5777,112.2922
26,ne,France,03/01/2020,130,2,12,47.0000,2.0000
27,ne,Germany,03/01/2020,130,0,16,51.0000,9.0000
28,ng,Mainland China,03/01/2020,122,1,103,41.2956,122.6085
29,ne,Singapore,03/01/2020,106,0,72,1.2833,103.8333
...,...,...,...,...,...,...,...,...
875,CA,US,03/09/2020,4,0,0,33.7879,-117.8531
876,NY,US,03/09/2020,4,0,0,41.1489,-73.9830
877,ec,Canada,03/09/2020,3,0,0,52.9399,-73.5491
878,FL,US,03/09/2020,3,0,0,26.1901,-80.3659
879,GA,US,03/09/2020,3,0,0,33.8999,-84.5641
880,NE,US,03/09/2020,3,0,0,41.3148,-96.1951
881,IA,US,03/09/2020,3,0,0,41.6699,-91.5984
882,CA,US,03/09/2020,3,0,0,38.5780,-122.9888
883,ne,Albania,03/09/2020,2,0,0,41.1533,20.1683
884,ne,Cyprus,03/09/2020,2,0,0,35.1264,33.4299
885,ne,Nigeria,03/09/2020,2,0,0,9.0820,8.6753
886,ne,St. Martin,03/09/2020,2,0,0,18.0708,-63.0501
887,KY,US,03/09/2020,2,0,0,38.4333,-84.3542
888,IN,US,03/09/2020,2,0,0,39.8065,-86.5401
889,HI,US,03/09/2020,2,0,0,21.3070,-157.8584
890,FL,US,03/09/2020,2,0,0,27.4799,-82.3452
891,ne,Brunei,03/09/2020,1,0,0,4.5353,114.7277
892,ne,Moldova,03/09/2020,1,0,0,47.4116,28.3699
893,ne,Saint Barthelemy,03/09/2020,1,0,0,17.9000,-62.8333
894,VT,US,03/09/2020,1,0,0,43.0279,-73.1350
895,MN,US,03/09/2020,1,0,0,44.8254,-93.7842
896,FL,US,03/09/2020,1,0,0,26.8946,-81.9098
897,GA,US,03/09/2020,1,0,0,34.2515,-84.4803
898,TX,US,03/09/2020,1,0,0,33.1795,-96.4930
899,WA,US,03/09/2020,1,1,0,47.1981,-119.3732
900,KY,US,03/09/2020,1,0,0,38.1938,-85.6435
901,LA,US,03/09/2020,1,0,0,29.6499,-90.1121
902,NH,US,03/09/2020,1,0,0,42.9931,-71.0498
903,CA,US,03/09/2020,1,0,0,40.7909,-121.8474
904,SC,US,03/09/2020,1,0,0,34.8606,-81.9535

In [10]:
dates2 = ['03-10', '03-11', '03-12', '03-13', '03-14', '03-15', '03-16', '03-17','03-18', '03-19', 
          '03-20', '03-21']

for x in range(len(dates2)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates2[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:10] + "/" + "2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
    abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

    for x in range(51):
        df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])
    
    df = df.append(df1, ignore_index = True)
    
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,ei,Mainland China,03/01/2020,66907,2761,31536,30.9756,112.2707
1,ne,South Korea,03/01/2020,3736,17,30,36.0000,128.0000
2,ne,Italy,03/01/2020,1694,34,83,43.0000,12.0000
3,ng,Mainland China,03/01/2020,1349,7,1016,23.3417,113.4244
4,an,Mainland China,03/01/2020,1272,22,1198,33.8820,113.6140
5,ng,Mainland China,03/01/2020,1205,1,1046,29.1832,120.0934
6,an,Mainland China,03/01/2020,1018,4,866,27.6104,111.7088
7,ui,Mainland China,03/01/2020,990,6,873,31.8257,117.2264
8,ne,Iran,03/01/2020,978,54,175,32.0000,53.0000
9,xi,Mainland China,03/01/2020,935,1,831,27.6140,115.7221
10,ng,Mainland China,03/01/2020,758,6,443,36.3427,118.1498
11,su,Mainland China,03/01/2020,631,0,536,32.9711,119.4550
12,ng,Mainland China,03/01/2020,576,6,450,30.0572,107.8740
13,an,Mainland China,03/01/2020,538,3,365,30.6171,102.7103
14,ng,Mainland China,03/01/2020,480,13,342,47.8620,127.7615
15,ng,Mainland China,03/01/2020,413,8,276,40.1824,116.4142
16,ai,Mainland China,03/01/2020,337,3,290,31.2020,121.4491
17,ei,Mainland China,03/01/2020,318,6,294,38.0428,114.5149
18,an,Mainland China,03/01/2020,296,1,247,26.0789,117.9874
19,ne,Japan,03/01/2020,256,6,32,36.0000,138.0000
20,xi,Mainland China,03/01/2020,252,2,181,23.8298,108.7881
21,xi,Mainland China,03/01/2020,245,1,208,35.1917,108.8701
22,an,Mainland China,03/01/2020,174,2,163,24.9740,101.4870
23,an,Mainland China,03/01/2020,168,5,149,19.1959,109.7453
24,in,Mainland China,03/01/2020,136,3,111,39.3054,117.3230
25,xi,Mainland China,03/01/2020,133,0,116,37.5777,112.2922
26,ne,France,03/01/2020,130,2,12,47.0000,2.0000
27,ne,Germany,03/01/2020,130,0,16,51.0000,9.0000
28,ng,Mainland China,03/01/2020,122,1,103,41.2956,122.6085
29,ne,Singapore,03/01/2020,106,0,72,1.2833,103.8333
...,...,...,...,...,...,...,...,...
2924,NaN,Kyrgyzstan,03/21/2020,14,0,0,41.2044,74.7661
2925,NaN,Mauritius,03/21/2020,14,1,0,-20.3484,57.5522
2926,NaN,Monaco,03/21/2020,11,0,0,43.7384,7.4246
2927,NaN,Mongolia,03/21/2020,10,0,0,46.8625,103.8467
2928,Australian Capital Territory,Australia,03/21/2020,9,0,0,-35.4735,149.0124
2929,WV,US,03/21/2020,8,0,0,38.4912,-80.9545
2930,NaN,Mayotte,03/21/2020,7,0,0,-12.8275,45.1662
2931,NaN,Barbados,03/21/2020,6,0,0,13.1939,-59.5432
2932,Newfoundland and Labrador,Canada,03/21/2020,6,0,0,53.1355,-57.6604
2933,United States Virgin Islands,US,03/21/2020,6,0,0,18.3358,-64.8963
2934,NaN,"Bahamas, The",03/21/2020,4,0,0,25.0343,-77.3963
2935,New Caledonia,France,03/21/2020,4,0,0,-20.9043,165.6180
2936,NaN,Gabon,03/21/2020,4,1,0,-0.8037,11.6094
2937,NaN,Cabo Verde,03/21/2020,3,0,0,16.5388,-23.0418
2938,NaN,El Salvador,03/21/2020,3,0,0,13.7942,-88.8965
2939,NaN,Liberia,03/21/2020,3,0,0,6.4281,-9.4295
2940,NaN,Zimbabwe,03/21/2020,3,0,0,-19.0154,29.1549
2941,NaN,Angola,03/21/2020,2,0,0,-11.2027,17.8739
2942,NaN,Guinea,03/21/2020,2,0,0,9.9456,-9.6966
2943,NaN,Haiti,03/21/2020,2,0,0,18.9712,-72.2852
2944,NaN,Nicaragua,03/21/2020,2,0,0,12.8654,-85.2072
2945,Bermuda,United Kingdom,03/21/2020,2,0,0,32.3078,-64.7505
2946,Northwest Territories,Canada,03/21/2020,1,0,0,64.8255,-124.8457
2947,NaN,Cape Verde,03/21/2020,1,0,0,15.1111,-23.6167
2948,NaN,Chad,03/21/2020,1,0,0,15.4542,18.7322
2949,NaN,East Timor,03/21/2020,1,0,0,-8.5500,125.5600
2950,NaN,Eritrea,03/21/2020,1,0,0,15.1794,39.7823
2951,NaN,Papua New Guinea,03/21/2020,1,0,0,-6.3150,143.9555
2952,US,US,03/21/2020,1,0,171,37.0902,-95.7129
2953,NaN,Uganda,03/21/2020,1,0,0,1.0000,32.0000

In [11]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv'
response = requests.get(url)

df1 = pd.read_csv(url)
df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]

df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[0:7] + "20")
mask = df1['Last Update'] == df1['Last Update'][0]
df1 = df1.loc[mask]

states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

for x in range(51):
    df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

df = df.append(df1, ignore_index = True)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,ei,Mainland China,03/01/2020,66907,2761,31536,30.975600,112.270700
1,ne,South Korea,03/01/2020,3736,17,30,36.000000,128.000000
2,ne,Italy,03/01/2020,1694,34,83,43.000000,12.000000
3,ng,Mainland China,03/01/2020,1349,7,1016,23.341700,113.424400
4,an,Mainland China,03/01/2020,1272,22,1198,33.882000,113.614000
5,ng,Mainland China,03/01/2020,1205,1,1046,29.183200,120.093400
6,an,Mainland China,03/01/2020,1018,4,866,27.610400,111.708800
7,ui,Mainland China,03/01/2020,990,6,873,31.825700,117.226400
8,ne,Iran,03/01/2020,978,54,175,32.000000,53.000000
9,xi,Mainland China,03/01/2020,935,1,831,27.614000,115.722100
10,ng,Mainland China,03/01/2020,758,6,443,36.342700,118.149800
11,su,Mainland China,03/01/2020,631,0,536,32.971100,119.455000
12,ng,Mainland China,03/01/2020,576,6,450,30.057200,107.874000
13,an,Mainland China,03/01/2020,538,3,365,30.617100,102.710300
14,ng,Mainland China,03/01/2020,480,13,342,47.862000,127.761500
15,ng,Mainland China,03/01/2020,413,8,276,40.182400,116.414200
16,ai,Mainland China,03/01/2020,337,3,290,31.202000,121.449100
17,ei,Mainland China,03/01/2020,318,6,294,38.042800,114.514900
18,an,Mainland China,03/01/2020,296,1,247,26.078900,117.987400
19,ne,Japan,03/01/2020,256,6,32,36.000000,138.000000
20,xi,Mainland China,03/01/2020,252,2,181,23.829800,108.788100
21,xi,Mainland China,03/01/2020,245,1,208,35.191700,108.870100
22,an,Mainland China,03/01/2020,174,2,163,24.974000,101.487000
23,an,Mainland China,03/01/2020,168,5,149,19.195900,109.745300
24,in,Mainland China,03/01/2020,136,3,111,39.305400,117.323000
25,xi,Mainland China,03/01/2020,133,0,116,37.577700,112.292200
26,ne,France,03/01/2020,130,2,12,47.000000,2.000000
27,ne,Germany,03/01/2020,130,0,16,51.000000,9.000000
28,ng,Mainland China,03/01/2020,122,1,103,41.295600,122.608500
29,ne,Singapore,03/01/2020,106,0,72,1.283300,103.833300
...,...,...,...,...,...,...,...,...
6325,NaN,Benin,03/22/2020,2,0,0,9.307700,2.315800
6326,Bermuda,United Kingdom,03/22/2020,2,0,0,32.307800,-64.750500
6327,NaN,Bhutan,03/22/2020,2,0,0,27.514200,90.433600
6328,NaN,Fiji,03/22/2020,2,0,0,-17.713400,178.065000
6329,NaN,Guinea,03/22/2020,2,0,0,9.945600,-9.696600
6330,NaN,Haiti,03/22/2020,2,0,0,18.971200,-72.285200
6331,NaN,Mauritania,03/22/2020,2,0,0,21.007900,10.940800
6332,NaN,Nicaragua,03/22/2020,2,0,0,12.865416,-85.207229
6333,NaN,Niger,03/22/2020,2,0,0,17.607789,8.081666
6334,NaN,Saint Lucia,03/22/2020,2,0,0,13.909400,-60.978900
6335,NaN,Nepal,03/22/2020,1,0,1,28.166700,84.250000
6336,NaN,Antigua and Barbuda,03/22/2020,1,0,0,17.060800,-61.796400
6337,NaN,Chad,03/22/2020,1,0,0,15.454200,18.732200
6338,NaN,Djibouti,03/22/2020,1,0,0,11.825100,42.590300
6339,NaN,Dominica,03/22/2020,1,0,0,15.415000,-61.371000
6340,NaN,Eritrea,03/22/2020,1,0,0,15.179400,39.782300
6341,NaN,Gambia,03/22/2020,1,0,0,13.443200,-15.310100
6342,NaN,Grenada,03/22/2020,1,0,0,12.116500,-61.679000
6343,NaN,Holy See,03/22/2020,1,0,0,41.902900,12.453400
6344,Montserrat,United Kingdom,03/22/2020,1,0,0,16.742498,-62.187366
6345,NaN,Mozambique,03/22/2020,1,0,0,-18.665695,35.529562
6346,NaN,Papua New Guinea,03/22/2020,1,0,0,-6.314993,143.955550
6347,NaN,Saint Vincent and the Grenadines,03/22/2020,1,0,0,12.984300,-61.287200
6348,Sint Maarten,Netherlands,03/22/2020,1,0,0,18.042500,-63.054800
6349,NaN,Somalia,03/22/2020,1,0,0,5.152149,46.199616
6350,NaN,Syria,03/22/2020,1,0,0,34.802075,38.996815
6351,NaN,Timor-Leste,03/22/2020,1,0,0,-8.874217,125.727539
6352,NaN,Uganda,03/22/2020,1,0,0,1.373333,32.290275
6353,DC,US,03/22/2020,102,2,0,38.904178,-77.016560
6354,WA,US,03/22/2020,1,2,0,46.451975,-117.545403

In [12]:
dates3 = ['03-23', '03-24', '03-25', '03-26', '03-27', '03-28', '03-29', '03-30', '03-31', '04-01',
         '04-03', '04-05', '04-07', '04-08', '04-09', '04-10', '04-11', '04-12', '04-13',
         '04-14', '04-15','04-16', '04-17', '04-18', '04-19', '04-20', '04-21']

for x in range(len(dates3)):
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/' + dates3[x] + '-2020.csv'
    response = requests.get(url)

    df1 = pd.read_csv(url)
    df1 = df1.rename(columns={"Province_State": "Province/State", "Country_Region": "Country/Region", "Last_Update": "Last Update", "Lat":"Latitude", "Long_":"Longitude"})
    df1 = df1[["Province/State", "Country/Region", "Last Update", "Confirmed", "Deaths", "Recovered", "Latitude", "Longitude"]]

    df1['Last Update'] = df1['Last Update'].apply(lambda x : "0" + x[6:10] + "/2020")
    df1['Last Update'] = df1['Last Update'].apply(lambda x : x.replace("-", "/"))
    mask = df1['Last Update'] == df1['Last Update'][0]
    df1 = df1.loc[mask]
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
          "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
          "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
          "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
          "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
          "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
          "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"]
    abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", 
       "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
       "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"]

    for x in range(51):
        df1["Province/State"] = df1["Province/State"].replace(states[x], abb[x])

    df = df.append(df1, ignore_index = True)
    
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,ei,Mainland China,03/01/2020,66907,2761,31536,30.975600,112.270700
1,ne,South Korea,03/01/2020,3736,17,30,36.000000,128.000000
2,ne,Italy,03/01/2020,1694,34,83,43.000000,12.000000
3,ng,Mainland China,03/01/2020,1349,7,1016,23.341700,113.424400
4,an,Mainland China,03/01/2020,1272,22,1198,33.882000,113.614000
5,ng,Mainland China,03/01/2020,1205,1,1046,29.183200,120.093400
6,an,Mainland China,03/01/2020,1018,4,866,27.610400,111.708800
7,ui,Mainland China,03/01/2020,990,6,873,31.825700,117.226400
8,ne,Iran,03/01/2020,978,54,175,32.000000,53.000000
9,xi,Mainland China,03/01/2020,935,1,831,27.614000,115.722100
10,ng,Mainland China,03/01/2020,758,6,443,36.342700,118.149800
11,su,Mainland China,03/01/2020,631,0,536,32.971100,119.455000
12,ng,Mainland China,03/01/2020,576,6,450,30.057200,107.874000
13,an,Mainland China,03/01/2020,538,3,365,30.617100,102.710300
14,ng,Mainland China,03/01/2020,480,13,342,47.862000,127.761500
15,ng,Mainland China,03/01/2020,413,8,276,40.182400,116.414200
16,ai,Mainland China,03/01/2020,337,3,290,31.202000,121.449100
17,ei,Mainland China,03/01/2020,318,6,294,38.042800,114.514900
18,an,Mainland China,03/01/2020,296,1,247,26.078900,117.987400
19,ne,Japan,03/01/2020,256,6,32,36.000000,138.000000
20,xi,Mainland China,03/01/2020,252,2,181,23.829800,108.788100
21,xi,Mainland China,03/01/2020,245,1,208,35.191700,108.870100
22,an,Mainland China,03/01/2020,174,2,163,24.974000,101.487000
23,an,Mainland China,03/01/2020,168,5,149,19.195900,109.745300
24,in,Mainland China,03/01/2020,136,3,111,39.305400,117.323000
25,xi,Mainland China,03/01/2020,133,0,116,37.577700,112.292200
26,ne,France,03/01/2020,130,2,12,47.000000,2.000000
27,ne,Germany,03/01/2020,130,0,16,51.000000,9.000000
28,ng,Mainland China,03/01/2020,122,1,103,41.295600,122.608500
29,ne,Singapore,03/01/2020,106,0,72,1.283300,103.833300
...,...,...,...,...,...,...,...,...
88466,NaN,South Africa,04/21/2020,3465,58,1055,-30.559500,22.937500
88467,NaN,South Sudan,04/21/2020,4,0,0,6.877000,31.307000
88468,NaN,Spain,04/21/2020,204178,21282,82514,40.463667,-3.749220
88469,NaN,Sri Lanka,04/21/2020,310,7,102,7.873054,80.771797
88470,NaN,Sudan,04/21/2020,107,12,8,12.862800,30.217600
88471,NaN,Suriname,04/21/2020,10,1,6,3.919300,-56.027800
88472,NaN,Sweden,04/21/2020,15322,1765,550,60.128161,18.643501
88473,NaN,Switzerland,04/21/2020,28063,1478,19400,46.818200,8.227500
88474,NaN,Syria,04/21/2020,42,3,6,34.802075,38.996815
88475,NaN,Taiwan*,04/21/2020,425,6,217,23.700000,121.000000
88476,NaN,Tanzania,04/21/2020,254,10,11,-6.369028,34.888822
88477,NaN,Thailand,04/21/2020,2811,48,2108,15.870032,100.992541
88478,NaN,Timor-Leste,04/21/2020,23,0,1,-8.874217,125.727539
88479,NaN,Togo,04/21/2020,86,6,56,8.619500,0.824800
88480,NaN,Trinidad and Tobago,04/21/2020,115,8,28,10.691800,-61.222500
88481,NaN,Tunisia,04/21/2020,884,38,148,33.886917,9.537499
88482,NaN,Turkey,04/21/2020,95591,2259,14918,38.963700,35.243300
88483,NaN,Uganda,04/21/2020,61,0,38,1.373333,32.290275
88484,NaN,Ukraine,04/21/2020,6125,161,367,48.379400,31.165600
88485,NaN,United Arab Emirates,04/21/2020,7755,46,1443,23.424076,53.847818
88486,NaN,United Kingdom,04/21/2020,129044,17337,0,55.378100,-3.436000
88487,NaN,Uruguay,04/21/2020,535,11,313,-32.522800,-55.765800
88488,NaN,Uzbekistan,04/21/2020,1678,6,357,41.377491,64.585262
88489,NaN,Venezuela,04/21/2020,285,10,117,6.423800,-66.589700
88490,NaN,Vietnam,04/21/2020,268,0,216,14.058324,108.277199
88491,NaN,West Bank and Gaza,04/21/2020,466,4,71,31.952200,35.233200
88492,NaN,Western Sahara,04/21/2020,6,0,0,24.215500,-12.885800
88493,NaN,Yemen,04/21/2020,1,0,0,15.552727,48.516388
88494,NaN,Zambia,04/21/2020,70,3,35,-13.133897,27.849332
88495,NaN,Zimbabwe,04/21/2020,28,3,2,-19.015438,29.154857

In [13]:
df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/LatLongdata.csv', index = False)

In [14]:
latlon = pd.read_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/LatLongdata.csv')
latlon

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,ei,Mainland China,03/01/2020,66907,2761,31536,30.975600,112.270700
1,ne,South Korea,03/01/2020,3736,17,30,36.000000,128.000000
2,ne,Italy,03/01/2020,1694,34,83,43.000000,12.000000
3,ng,Mainland China,03/01/2020,1349,7,1016,23.341700,113.424400
4,an,Mainland China,03/01/2020,1272,22,1198,33.882000,113.614000
5,ng,Mainland China,03/01/2020,1205,1,1046,29.183200,120.093400
6,an,Mainland China,03/01/2020,1018,4,866,27.610400,111.708800
7,ui,Mainland China,03/01/2020,990,6,873,31.825700,117.226400
8,ne,Iran,03/01/2020,978,54,175,32.000000,53.000000
9,xi,Mainland China,03/01/2020,935,1,831,27.614000,115.722100
10,ng,Mainland China,03/01/2020,758,6,443,36.342700,118.149800
11,su,Mainland China,03/01/2020,631,0,536,32.971100,119.455000
12,ng,Mainland China,03/01/2020,576,6,450,30.057200,107.874000
13,an,Mainland China,03/01/2020,538,3,365,30.617100,102.710300
14,ng,Mainland China,03/01/2020,480,13,342,47.862000,127.761500
15,ng,Mainland China,03/01/2020,413,8,276,40.182400,116.414200
16,ai,Mainland China,03/01/2020,337,3,290,31.202000,121.449100
17,ei,Mainland China,03/01/2020,318,6,294,38.042800,114.514900
18,an,Mainland China,03/01/2020,296,1,247,26.078900,117.987400
19,ne,Japan,03/01/2020,256,6,32,36.000000,138.000000
20,xi,Mainland China,03/01/2020,252,2,181,23.829800,108.788100
21,xi,Mainland China,03/01/2020,245,1,208,35.191700,108.870100
22,an,Mainland China,03/01/2020,174,2,163,24.974000,101.487000
23,an,Mainland China,03/01/2020,168,5,149,19.195900,109.745300
24,in,Mainland China,03/01/2020,136,3,111,39.305400,117.323000
25,xi,Mainland China,03/01/2020,133,0,116,37.577700,112.292200
26,ne,France,03/01/2020,130,2,12,47.000000,2.000000
27,ne,Germany,03/01/2020,130,0,16,51.000000,9.000000
28,ng,Mainland China,03/01/2020,122,1,103,41.295600,122.608500
29,ne,Singapore,03/01/2020,106,0,72,1.283300,103.833300
...,...,...,...,...,...,...,...,...
88466,NaN,South Africa,04/21/2020,3465,58,1055,-30.559500,22.937500
88467,NaN,South Sudan,04/21/2020,4,0,0,6.877000,31.307000
88468,NaN,Spain,04/21/2020,204178,21282,82514,40.463667,-3.749220
88469,NaN,Sri Lanka,04/21/2020,310,7,102,7.873054,80.771797
88470,NaN,Sudan,04/21/2020,107,12,8,12.862800,30.217600
88471,NaN,Suriname,04/21/2020,10,1,6,3.919300,-56.027800
88472,NaN,Sweden,04/21/2020,15322,1765,550,60.128161,18.643501
88473,NaN,Switzerland,04/21/2020,28063,1478,19400,46.818200,8.227500
88474,NaN,Syria,04/21/2020,42,3,6,34.802075,38.996815
88475,NaN,Taiwan*,04/21/2020,425,6,217,23.700000,121.000000
88476,NaN,Tanzania,04/21/2020,254,10,11,-6.369028,34.888822
88477,NaN,Thailand,04/21/2020,2811,48,2108,15.870032,100.992541
88478,NaN,Timor-Leste,04/21/2020,23,0,1,-8.874217,125.727539
88479,NaN,Togo,04/21/2020,86,6,56,8.619500,0.824800
88480,NaN,Trinidad and Tobago,04/21/2020,115,8,28,10.691800,-61.222500
88481,NaN,Tunisia,04/21/2020,884,38,148,33.886917,9.537499
88482,NaN,Turkey,04/21/2020,95591,2259,14918,38.963700,35.243300
88483,NaN,Uganda,04/21/2020,61,0,38,1.373333,32.290275
88484,NaN,Ukraine,04/21/2020,6125,161,367,48.379400,31.165600
88485,NaN,United Arab Emirates,04/21/2020,7755,46,1443,23.424076,53.847818
88486,NaN,United Kingdom,04/21/2020,129044,17337,0,55.378100,-3.436000
88487,NaN,Uruguay,04/21/2020,535,11,313,-32.522800,-55.765800
88488,NaN,Uzbekistan,04/21/2020,1678,6,357,41.377491,64.585262
88489,NaN,Venezuela,04/21/2020,285,10,117,6.423800,-66.589700
88490,NaN,Vietnam,04/21/2020,268,0,216,14.058324,108.277199
88491,NaN,West Bank and Gaza,04/21/2020,466,4,71,31.952200,35.233200
88492,NaN,Western Sahara,04/21/2020,6,0,0,24.215500,-12.885800
88493,NaN,Yemen,04/21/2020,1,0,0,15.552727,48.516388
88494,NaN,Zambia,04/21/2020,70,3,35,-13.133897,27.849332
88495,NaN,Zimbabwe,04/21/2020,28,3,2,-19.015438,29.154857

In [15]:
mask = latlon["Country/Region"] == "US"
df = latlon.loc[mask]
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
50,WA,US,03/01/2020,9,1,1,47.606200,-122.332100
63,IL,US,03/01/2020,3,0,2,41.878100,-87.629800
67,WA,US,03/01/2020,2,0,0,48.033000,-121.833900
73,RI,US,03/01/2020,1,0,0,41.824000,-71.412800
113,s),US,03/02/2020,45,0,0,35.443700,139.638000
124,WA,US,03/02/2020,14,5,1,47.548000,-121.983600
127,CA,US,03/02/2020,9,0,1,37.354100,-121.955200
132,IL,US,03/02/2020,4,0,2,41.737700,-87.697600
133,WA,US,03/02/2020,4,1,0,48.033000,-121.833900
139,OR,US,03/02/2020,2,0,0,45.505100,-122.675000
140,RI,US,03/02/2020,2,0,0,41.824000,-71.412800
148,NH,US,03/02/2020,1,0,0,43.908800,-71.826000
149,FL,US,03/02/2020,1,0,0,27.990400,-82.301800
150,NY,US,03/02/2020,1,0,0,40.712800,-74.006000
151,CA,US,03/02/2020,1,0,0,39.091600,-120.803900
152,CA,US,03/02/2020,1,0,0,37.563000,-122.325500
153,FL,US,03/02/2020,1,0,0,27.336400,-82.530700
154,CA,US,03/02/2020,1,0,0,38.578000,-122.988800
155,OR,US,03/02/2020,1,0,0,45.775000,-118.760600
201,WA,US,03/03/2020,21,6,1,47.548000,-121.983600
209,CA,US,03/03/2020,11,0,1,37.354100,-121.955200
217,WA,US,03/03/2020,6,1,0,48.033000,-121.833900
227,GA,US,03/03/2020,2,0,0,33.803400,-84.396300
228,NH,US,03/03/2020,2,0,0,43.908800,-71.826000
229,FL,US,03/03/2020,2,0,0,27.990400,-82.301800
230,CA,US,03/03/2020,2,0,0,37.563000,-122.325500
231,OR,US,03/03/2020,2,0,0,45.547000,-123.138600
237,MA,US,03/03/2020,1,0,0,42.176700,-71.144900
238,CA,US,03/03/2020,1,0,0,37.871500,-122.273000
239,WI,US,03/03/2020,1,0,1,43.073100,-89.401200
...,...,...,...,...,...,...,...,...
88223,OR,US,04/21/2020,35,6,0,45.233304,-123.308696
88224,SD,US,04/21/2020,23,0,0,43.009245,-97.394676
88225,NY,US,04/21/2020,10,0,0,42.635055,-77.103699
88226,AZ,US,04/21/2020,72,1,0,34.599339,-112.553859
88227,MS,US,04/21/2020,103,1,0,32.778904,-90.396561
88228,AR,US,04/21/2020,2,0,0,35.002924,-93.411713
88229,MN,US,04/21/2020,3,0,0,44.717102,-95.868425
88230,MT,US,04/21/2020,73,1,0,45.939559,-108.269149
88231,TX,US,04/21/2020,1,0,0,33.173202,-102.827643
88232,CA,US,04/21/2020,142,10,0,38.682789,-121.901829
88233,ME,US,04/21/2020,183,6,0,43.478084,-70.710524
88234,NE,US,04/21/2020,7,0,0,40.872726,-97.597102
88235,PA,US,04/21/2020,517,13,0,39.921009,-76.730401
88236,SC,US,04/21/2020,159,3,0,34.972815,-81.180859
88237,VA,US,04/21/2020,43,1,0,37.243748,-76.544128
88238,TX,US,04/21/2020,4,1,0,33.176597,-98.687909
88239,CA,US,04/21/2020,16,1,0,39.262559,-121.353564
88240,AK,US,04/21/2020,1,0,0,65.508155,-151.390739
88241,AZ,US,04/21/2020,32,1,0,32.768957,-113.906667
88242,CO,US,04/21/2020,3,0,0,40.003468,-102.425867
88243,TX,US,04/21/2020,6,0,0,27.001564,-99.169872
88244,TX,US,04/21/2020,1,0,0,28.866172,-99.760508
88257,Diamond Princess,US,04/21/2020,49,0,0,NaN,NaN
88265,Grand Princess,US,04/21/2020,103,0,0,NaN,NaN
88268,Guam,US,04/21/2020,136,5,0,13.444300,144.793700
88286,Northern Mariana Islands,US,04/21/2020,14,2,0,15.097900,145.673900
88292,Puerto Rico,US,04/21/2020,1298,64,0,18.220800,-66.590100
88296,Recovered,US,04/21/2020,0,0,75204,NaN,NaN
88309,Veteran Hospitals,US,04/21/2020,5599,357,0,NaN,NaN
88311,Virgin Islands,US,04/21/2020,53,3,0,18.335800,-64.896300

In [16]:
df.to_csv('/Users/markomiholjcic/Documents/GitHub/COMP5360Project/project_files/csv_files/USLatLon.csv', index = False)